/**
 * Hospital formulary drug list for pharmacy interaction checker.
 * Cross-referenced: 陽明院區常備藥品明細表 × MICROMEDEX DrugDex.
 * 490 with data + 278 without = 768 total.
 */

/** Drugs with MICROMEDEX interaction data */
export const DRUGS_WITH_DATA: string[] = [
  "Abacavir",
  "Acarbose",
  "Acemetacin",
  "Acetaminophen",
  "AcetaZOLAMIDE",
  "Acetylcysteine",
  "Acitretin",
  "Acyclovir (Systemic)",
  "Adenosine",
  "Agomelatine",
  "Albuterol",
  "Alendronate",
  "Alfacalcidol",
  "ALfentanil",
  "Alfuzosin",
  "Allopurinol",
  "ALPRAZolam",
  "Alprostadil",
  "Alteplase",
  "Aluminum Hydroxide",
  "Amantadine",
  "Aminophylline",
  "Amiodarone",
  "Amisulpride (Injection)",
  "Amisulpride (Oral)",
  "AmLODIPine",
  "Amoxicillin",
  "Amphotericin B",
  "Ampicillin",
  "Anagrelide",
  "Anastrozole",
  "Apixaban",
  "ARIPiprazole",
  "Ascorbic Acid",
  "Aspirin",
  "Atenolol",
  "Atorvastatin",
  "Atropine (Ophthalmic)",
  "Atropine (Systemic)",
  "AzaTHIOprine",
  "Azelastine (Nasal)",
  "Azithromycin (Systemic)",
  "Baclofen",
  "Bazedoxifene",
  "Bempedoic Acid",
  "Benzbromarone",
  "Benzoyl Peroxide",
  "Betahistine",
  "Betamethasone (Nasal)",
  "Betamethasone (Ophthalmic)",
  "Betamethasone (Systemic)",
  "Betamethasone (Topical)",
  "Bevacizumab",
  "Bezafibrate",
  "Bicalutamide",
  "Bimatoprost",
  "Biperiden",
  "Bisacodyl",
  "Bisoprolol",
  "Bortezomib",
  "Brexpiprazole",
  "Brimonidine (Ophthalmic)",
  "Brimonidine (Topical)",
  "Bromazepam",
  "Bromocriptine",
  "Brompheniramine",
  "Brotizolam",
  "Budesonide (Nasal)",
  "Budesonide (Oral Inhalation)",
  "Budesonide (Systemic)",
  "Budesonide (Topical)",
  "BUPivacaine",
  "BUPivacaine (Liposomal)",
  "Buprenorphine",
  "BuPROPion",
  "BusPIRone",
  "Cabergoline",
  "Calcitonin",
  "Calcitriol (Systemic)",
  "Calcium Acetate",
  "Calcium Carbonate",
  "Canagliflozin",
  "Candesartan",
  "Carbachol",
  "CarBAMazepine",
  "Carbidopa",
  "CARBOplatin",
  "Carisoprodol",
  "Carvedilol",
  "CeFAZolin",
  "Cefmetazole",
  "Cefoperazone",
  "Cefpirome",
  "CefTAZidime",
  "Ceftizoxime",
  "CefTRIAXone",
  "Cefuroxime",
  "Celecoxib",
  "Cephalexin",
  "Cephradine",
  "Cetirizine (Systemic)",
  "Chloral Hydrate/Chloral Betaine",
  "Cholestyramine Resin",
  "Ciclesonide (Oral Inhalation)",
  "Cilostazol",
  "Cinacalcet",
  "Ciprofloxacin (Ophthalmic)",
  "Ciprofloxacin (Systemic)",
  "CISplatin",
  "Citalopram",
  "Clarithromycin",
  "Clindamycin (Systemic)",
  "Clindamycin (Topical)",
  "ClomiPHENE",
  "ClonazePAM",
  "CloNIDine",
  "Clopidogrel",
  "CloZAPine",
  "Codeine",
  "Colchicine",
  "Crisaborole",
  "Cyclobenzaprine",
  "CycloPHOSphamide",
  "Cyproheptadine",
  "Cyproterone",
  "Dapagliflozin",
  "Dapoxetine",
  "Darbepoetin Alfa",
  "Deferoxamine",
  "Denosumab",
  "Desloratadine",
  "Desmopressin",
  "DexAMETHasone (Ophthalmic)",
  "DexAMETHasone (Systemic)",
  "Dexamethasone (Topical)",
  "Dexlansoprazole",
  "DexmedeTOMIDine",
  "Dextran",
  "Dextromethorphan",
  "DiazePAM",
  "Diclofenac (Systemic)",
  "Dicloxacillin",
  "Digoxin",
  "DilTIAZem",
  "Dimethicone (Systemic)",
  "DiphenhydrAMINE (Systemic)",
  "Dipyridamole",
  "DOBUTamine",
  "DOCEtaxel",
  "Domperidone",
  "Donepezil",
  "DOPamine",
  "Doxazosin",
  "Doxepin (Systemic)",
  "Doxepin (Topical)",
  "DOXOrubicin (Conventional)",
  "DOXOrubicin (Liposomal)",
  "Doxycycline",
  "Drospirenone-Containing Products",
  "DULoxetine",
  "Dupilumab",
  "Dutasteride",
  "Dydrogesterone",
  "Edoxaban",
  "Efavirenz",
  "Emedastine (Systemic)",
  "Empagliflozin",
  "Entacapone",
  "EPHEDrine (Nasal)",
  "EPHEDrine (Systemic)",
  "EPINEPHrine (Oral Inhalation)",
  "Epinephrine (Racemic)",
  "EPINEPHrine (Systemic)",
  "Eplerenone",
  "Ergonovine",
  "Ertapenem",
  "Escitalopram",
  "Esomeprazole",
  "Estazolam",
  "Ethambutol",
  "Etofenamate",
  "Etoricoxib",
  "Ezetimibe",
  "Famciclovir",
  "Famotidine",
  "Febuxostat",
  "Felodipine",
  "Fenofibrate and Derivatives",
  "Fenoterol",
  "FentaNYL",
  "Fexofenadine",
  "Filgrastim",
  "Finasteride",
  "Fluconazole",
  "Flunarizine",
  "Flunitrazepam",
  "Fluorouracil (Systemic)",
  "FLUoxetine",
  "Flupentixol",
  "Flurazepam",
  "Flurbiprofen (Systemic)",
  "Fluticasone (Nasal)",
  "Fluticasone (Oral Inhalation)",
  "Fluticasone (Topical)",
  "Fluvastatin",
  "FluvoxaMINE",
  "Folic Acid",
  "Formoterol",
  "Fosfomycin",
  "Fosinopril",
  "Furosemide",
  "Fusidic Acid (Systemic)",
  "Gabapentin (Immediate Release)",
  "Gemcitabine (Systemic)",
  "Gemifloxacin",
  "Gentamicin (Systemic)",
  "Gliclazide",
  "Glimepiride",
  "Glucosamine",
  "GlyBURIDE",
  "Glycopyrrolate (Oral Inhalation)",
  "Glycopyrrolate (Systemic)",
  "Haloperidol",
  "Heparin",
  "HydrALAZINE",
  "Hydrocortisone (Ophthalmic)",
  "Hydrocortisone (Systemic)",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "HydrOXYzine",
  "Ibuprofen (Systemic)",
  "Imidapril",
  "Imipenem",
  "Imipramine",
  "Indacaterol",
  "Indomethacin (Systemic)",
  "Insulin",
  "Ipratropium (Nasal)",
  "Ipratropium (Oral Inhalation)",
  "Irbesartan",
  "Irinotecan Products",
  "Isoconazole",
  "Isoniazid",
  "ISOtretinoin (Systemic)",
  "Itraconazole",
  "Ivabradine",
  "Ketoconazole (Systemic)",
  "Ketoprofen",
  "Ketorolac (Nasal)",
  "Ketorolac (Systemic)",
  "Ketotifen (Systemic)",
  "Labetalol",
  "Lacidipine",
  "Lacosamide",
  "Lactulose",
  "LamiVUDine",
  "LamoTRIgine",
  "Lansoprazole",
  "Latanoprost",
  "Lercanidipine",
  "Letrozole",
  "LevETIRAcetam",
  "Levocetirizine",
  "LevoFLOXacin (Systemic)",
  "Levothyroxine",
  "Lidocaine (Systemic)",
  "Lidocaine (Topical)",
  "LinaGLIPtin",
  "Linezolid",
  "Liraglutide",
  "Lithium",
  "Loperamide",
  "Loratadine",
  "LORazepam",
  "Losartan",
  "Lovastatin",
  "Lurasidone",
  "Mannitol (Systemic)",
  "Mebendazole",
  "MedroxyPROGESTERone",
  "Mefenamic Acid",
  "Megestrol",
  "Melatonin",
  "Meloxicam",
  "Memantine",
  "Meperidine",
  "Meropenem",
  "Mesalamine",
  "MetFORMIN",
  "Methadone",
  "MethIMAzole",
  "Methotrexate",
  "Methylergonovine",
  "Methylphenidate",
  "MethylPREDNISolone (Systemic)",
  "MethylPREDNISolone (Topical)",
  "Metoclopramide",
  "Metoprolol",
  "MetroNIDAZOLE (Systemic)",
  "MetroNIDAZOLE (Topical)",
  "Mexiletine",
  "Midazolam",
  "Midodrine",
  "MiFEPRIStone",
  "Milnacipran",
  "Mineral Oil",
  "Minocycline (Systemic)",
  "Minocycline (Topical)",
  "Mirabegron",
  "Mirtazapine",
  "MiSOPROStol",
  "Mizolastine",
  "Mometasone (Nasal)",
  "Mometasone (Oral Inhalation)",
  "Mometasone (Topical)",
  "Montelukast",
  "Morphine (Systemic)",
  "Moxifloxacin (Systemic)",
  "Naloxone",
  "Nebivolol",
  "Neomycin (Systemic)",
  "Neomycin (Topical)",
  "NiCARdipine",
  "Nicergoline",
  "Nicorandil",
  "Nicotine",
  "NIFEdipine (Systemic)",
  "NIFEdipine (Topical)",
  "Nintedanib",
  "Nisoldipine",
  "Nitroglycerin",
  "Norepinephrine",
  "Octreotide",
  "Ofloxacin (Systemic)",
  "OLANZapine",
  "Olmesartan",
  "Omeprazole",
  "Oseltamivir",
  "Oxaliplatin",
  "OXcarbazepine",
  "OxyBUTYnin",
  "OxyCODONE",
  "Oxymetazoline (Ophthalmic)",
  "Oxymetazoline (Topical)",
  "Oxytocin",
  "PACLitaxel (Conventional)",
  "PACLitaxel (Protein Bound)",
  "Pancrelipase",
  "Pantoprazole",
  "Parecoxib",
  "PEMEtrexed",
  "Penicillin G",
  "Pentoxifylline",
  "Perampanel",
  "PHENobarbital",
  "Phenytoin",
  "Phytonadione",
  "Pilocarpine (Ophthalmic)",
  "Pilocarpine (Systemic)",
  "Pimecrolimus",
  "Pimozide",
  "Pioglitazone",
  "Pipemidic Acid",
  "Piperacillin",
  "Piracetam",
  "Pirfenidone",
  "Pitavastatin",
  "Polymyxin B",
  "Potassium Chloride",
  "Potassium Citrate",
  "Pramipexole",
  "Prasugrel",
  "Pravastatin",
  "PrednisoLONE (Systemic)",
  "PrednisoLONE (Topical)",
  "Pregabalin",
  "Prochlorperazine",
  "Progesterone",
  "Propacetamol",
  "Propafenone",
  "Propofol",
  "Propranolol",
  "Propylthiouracil",
  "Pseudoephedrine",
  "Pyrazinamide",
  "QUEtiapine",
  "Quinapril",
  "RABEprazole",
  "Racecadotril",
  "Raloxifene",
  "Ramelteon",
  "Ramipril",
  "RaNITIdine",
  "Rasagiline",
  "Repaglinide",
  "Ribavirin (Oral Inhalation)",
  "Ribavirin (Systemic)",
  "RifAMPin",
  "RisperiDONE",
  "Ritodrine",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Rosuvastatin",
  "Salicylic Acid",
  "SAXagliptin",
  "Scopolamine",
  "Semaglutide",
  "Sertraline",
  "Sevoflurane",
  "Sildenafil",
  "Simethicone",
  "Simvastatin",
  "SITagliptin",
  "Sodium Bicarbonate (Systemic)",
  "Sodium Chloride",
  "Sofosbuvir",
  "Solifenacin",
  "Spironolactone",
  "Strontium Ranelate",
  "Succinylcholine",
  "Sucralfate",
  "Sulbactam",
  "SulfADIAZINE",
  "Sulfamethoxazole",
  "SulfaSALAzine",
  "Sulfinpyrazone",
  "Sulpiride",
  "Tacrolimus (Systemic)",
  "Tacrolimus (Topical)",
  "Tadalafil",
  "Tamoxifen",
  "Tamsulosin",
  "Tazarotene",
  "Teicoplanin",
  "Telmisartan",
  "Tenoxicam",
  "Terazosin",
  "Terbinafine (Systemic)",
  "Terbutaline",
  "Testosterone",
  "Tetracycline (Systemic)",
  "Thalidomide",
  "Theophylline",
  "Thiamine",
  "TiaGABine",
  "Ticlopidine",
  "Tigecycline",
  "Timolol (Ophthalmic)",
  "Timolol (Systemic)",
  "Tiotropium",
  "Tirzepatide",
  "Tobramycin (Oral Inhalation)",
  "Tolperisone",
  "Tolterodine",
  "Topiramate",
  "Torsemide",
  "TraMADol",
  "Tranexamic Acid",
  "Trastuzumab",
  "TraZODone",
  "Triamcinolone (Nasal)",
  "Triamcinolone (Ophthalmic)",
  "Triamcinolone (Systemic)",
  "Triamcinolone (Topical)",
  "Triazolam",
  "Trihexyphenidyl",
  "Triprolidine",
  "Tropicamide",
  "Ulipristal",
  "Urokinase",
  "Vadadustat",
  "Valproic Acid and Derivatives",
  "Valsartan",
  "Vancomycin",
  "Varicella Virus Vaccine",
  "Vasopressin",
  "Venlafaxine",
  "Verapamil",
  "Vilanterol",
  "VinCRIStine",
  "Vinorelbine",
  "Voriconazole",
  "Vortioxetine",
  "Warfarin",
  "Zaleplon",
  "Ziprasidone",
  "Zoledronic Acid",
  "Zolpidem",
  "Zopiclone",
];

/** Hospital drugs WITHOUT interaction data */
export const DRUGS_WITHOUT_DATA: string[] = [
  "Acebutolol",
  "Aceclofenac",
  "Acrinol",
  "Activated Charcoal",
  "Adapalene",
  "Alginic Acid",
  "Aluminum dihydroxyallantoin",
  "Alverine",
  "Ambroxol",
  "Ambroxol Sol'n",
  "Amikacin",
  "Amino Acid",
  "Amino acids",
  "Amio Acid",
  "Amorolfine",
  "Ampicillin Sod",
  "Amylase alpha",
  "Antazoline",
  "Antica",
  "Antivenin of B.multicinctus and N.naja arta",
  "Antivenin of TR",
  "Azapentacene Polysulfonate",
  "Azelaic Acid",
  "Azilsartan modoxomil",
  "Beclometh",
  "Benralizumab",
  "Benserazide",
  "Benzonatate",
  "Benzydamine",
  "Benzyl Benzoate",
  "Betamethasone,Clotrimazole,Gentamycin",
  "Betaxolol",
  "Bethanechol",
  "Botulinum Toxin Type A",
  "Brinzolamide",
  "Bromelain",
  "Bromhexine",
  "Buformin",
  "Bumetanide",
  "Bunazosin HCl R",
  "Butenafine",
  "Butinolin",
  "C.B.Strong",
  "Cadexomer Iodine",
  "Calamine",
  "Calcipotriol",
  "Calcitonin Synthetic Salmon",
  "Calcium",
  "CALCIUM CHLORIDE, GLUCOSE",
  "Calcium Folinate",
  "Calcium Polystyrene Sulfonate Ca 7-",
  "Calcium, Vitamin D2",
  "Candesartan Cilexetil",
  "Carbomer",
  "Carteolol",
  "Castor oil",
  "Cefepime",
  "Cefixime",
  "Cefixmycin",
  "Cefoxitin",
  "Ceftaroline",
  "CETYLPYRIDINIUM CHLORIDE、EPHEDRINE HCL (EQ TO EPHEDRINE HYDROCHLORIDE)、LIDOCAINE HCL、TYROTHRICIN",
  "Chloral",
  "Chlorhexidine",
  "Chlorpheniramine Maleate, Platycodon Fl. Ext., Polygala Fl. Ext., Glycyrrhizine",
  "Cholecalciferol",
  "Cholecaleiferol",
  "Ciclopirox",
  "Cinchocaine",
  "Cisatracurium",
  "Clobetasol",
  "Clostridium butyricum miyairi",
  "Clotiapine",
  "Colistin",
  "Crotamiton",
  "Cyanocobalamin",
  "Dabigatran",
  "Dalteparin",
  "Desoximetasone",
  "DEXTROSE",
  "Dianeal",
  "Dianeal Low Ca",
  "Dihydroergotoxine",
  "Dimemorfan",
  "Dioctahedral smectite",
  "Diphenidol",
  "Diquafosol",
  "Dorzolamide",
  "Duasorb",
  "Dulaglutide",
  "Engene",
  "Enoxolone (Glycyrrhetic Acid), Benzocaine, Lidocaine, Phenylephrine, Bismuth",
  "Entecavir",
  "Entresto",
  "Epoetin Beta",
  "Eraxis",
  "Ergotamine",
  "Escin 10㎎、Heparinoid 10㎎、Diethylamine Salicylate 50㎎",
  "Estradiol",
  "Estradiol 1,Medroxyprogesterone",
  "ESTROGEN",
  "Ethanol",
  "Etodolac",
  "Evac",
  "Felinamin",
  "Fenticonazole",
  "Ferric chloride hexahydrate",
  "Ferrous",
  "Flavoxate",
  "Flomoxef",
  "Fludiazepam",
  "Flumazenil",
  "Fluocinonide",
  "Fluorescein",
  "Fluorometholone",
  "Flutamide",
  "Framycetin",
  "Fusidate",
  "Gancicure",
  "Gelofusine",
  "Ginkgo flavonglycoside",
  "GLUCOSE",
  "Glycerol",
  "GLYCYRRHIZA EXTRACT",
  "Glycyrrhizic",
  "Glycyrrhizin",
  "Gowell or the same formula",
  "Granisetron",
  "Halcinonide Micro",
  "Hatermas",
  "Hepatitis A Virus Vaccine",
  "Hepatitis A,Antiger",
  "Hepatitis B immune Globulin S",
  "Hepatitis B Vaccine",
  "Histapp Gr. or the same formula",
  "Human",
  "Human Albumin",
  "Human Rotairus",
  "Human Serum Protein",
  "Hydrocortisone Sod",
  "Hydrogen Peroxide",
  "Hydroquinone",
  "Hyoscine Butylbromide",
  "Hypromellose eye drops",
  "Ibandronic acid",
  "Icodextrin",
  "Imiquimod",
  "Inactivated EV71 vaccine",
  "Indapamide",
  "Indocyanine green",
  "Insulim aspart",
  "Insulin Aspart",
  "Insulin Degludec",
  "Insulin Detemir",
  "Insulin Glargine",
  "Insulin Human NPH",
  "Iron",
  "Iron Sucrose complex",
  "Isavuconazole",
  "Isepamicin",
  "Isosorbide-5-Mononitrate",
  "Kaolin and Pectin",
  "Ketosteril 包含五種必需胺基酸(Essential Amino Acid)和五種必需胺基酸的α-酮酸",
  "Kitasamycin",
  "L-Carnitine",
  "Lactobacillus Bifidus",
  "Lactobacteria",
  "Leuprorelin",
  "Levonorgestrel,Ethinylestradiol",
  "Lidocaine ,Epinephri",
  "Lidocaine,Prilocaine",
  "Mag. Aluminium Silicate",
  "Magaldrate",
  "Magvac",
  "Measles, Mumps, Rubella",
  "Mecobalamin",
  "Meningococcal Group B Vaccine",
  "Mepenzolate",
  "Mepolizumab",
  "Mesna",
  "Metolazone",
  "Miglitol",
  "Mitomycin-C",
  "Montelukast Sod",
  "Mosapride",
  "NaCl",
  "NaCl, KCl, CaCl2, Sodium",
  "Naftifine",
  "Nemonoxacin",
  "Neomycin, Tyrothricin",
  "Neostigmine",
  "Nicametate",
  "Nordazepam",
  "Norethisterone",
  "Nystatin",
  "Omacor",
  "Omalizumab",
  "Omidenepag",
  "Otilonium",
  "Oxacillin",
  "Oxazepam",
  "Oxethazaine",
  "Paliperidone Palmitate",
  "Pamidronate",
  "Pancreatin",
  "PEG3350, Sodium",
  "Peginterferon Alfa-2a",
  "Peridopril",
  "Perindopril",
  "Pertussis,Diphtheria,Tetanus Toxoids",
  "Phenprobamate",
  "Phosphoric acid",
  "Picosulfate",
  "Pinaverium",
  "Pipoxolan",
  "Pirenoxine",
  "Piroxicam",
  "Piroxicam Beta-cyclodextrin",
  "Pneumococcal vaccine 23價肺炎鏈球菌",
  "Policresulen vag",
  "Polytar",
  "Potassium",
  "Povidone iodine",
  "Povidone-Iodine Aqu. Sol'n",
  "Procaterol",
  "Proparacaine",
  "Psyllium hydrophilic mucilloid",
  "Quadrivalent Human",
  "Ranibizumab",
  "Rinderon-VA",
  "Rituximab",
  "Ropinirole FC",
  "Rotavirus vaccine",
  "RSV vaccine",
  "Sennapur",
  "Sennoside",
  "Sertaconazole",
  "Sevina or the same formula",
  "Silymarin",
  "Sod. Bicarbonate",
  "Sodium",
  "Sodium phosphate dibasic",
  "Sofradex",
  "Sorbitol, NaCl, KCl, CaCl2",
  "Spherical absorptive carbon",
  "Sterculia",
  "Streptococcus Faecalis Lactomin(乳酸菌)、Clostridium Butyricum Butyric Acid Bacteria(酪酸菌)、Bacillus MesentericusAmylolytic Bacillus",
  "Sulconazole",
  "Sultamicillin",
  "Survanta",
  "Tafluprost",
  "Taigexyn",
  "Taita Sol'n No.5",
  "Tegafur",
  "Telbivudine",
  "Tenofovir disoproxil",
  "Teriparatide",
  "Terlipressin",
  "Tetanus Toxoid",
  "Thiamylal",
  "Tocilizumab",
  "Trace element",
  "Travoprost",
  "Trichlormethiazide",
  "Tripotassium dicitrate bismuthate",
  "Urea",
  "Ursodeoxycholic Acid",
  "Valaciclovir",
  "Varennicline",
  "Vidagliptin",
  "Water for",
  "Zanamivir",
  "Zinc",
  "Zinc Sulfate,Vit.C",
  "ZincOxide",
  "Zoster virus vaccine",
  "Zotepine",
  "自費]Flucelvax 4價",
];

/** All hospital drugs combined */
export const DRUG_LIST: string[] = [...DRUGS_WITH_DATA, ...DRUGS_WITHOUT_DATA];

/** Quick lookup: does this drug have interaction data? */
const _withDataLower = new Set(DRUGS_WITH_DATA.map(d => d.toLowerCase()));
export function hasInteractionData(drug: string): boolean {
  return _withDataLower.has(drug.toLowerCase());
}
