/**
 * Master drug list for pharmacy combobox selectors.
 * Generated from MICROMEDEX DrugDex full interaction dataset (2,164 drugs).
 * Sorted alphabetically, case-insensitive.
 */
export const DRUG_LIST: string[] = [
  "5-Aminosalicylic Acid Derivatives",
  "ALPRAZolam",
  "ALfentanil",
  "AMILoride",
  "ARIPiprazole",
  "ARIPiprazole Lauroxil",
  "Abacavir",
  "Abatacept",
  "Abciximab",
  "Abemaciclib",
  "Abiraterone Acetate",
  "Abrocitinib",
  "Acacia Gum",
  "Acalabrutinib",
  "Acarbose",
  "Acebrophylline",
  "Acemetacin",
  "AcetaZOLAMIDE",
  "Acetaminophen",
  "Acetylcholinesterase Inhibitors",
  "Acetylcysteine",
  "Acipimox",
  "Acitretin",
  "Aclidinium",
  "Acoramidis",
  "Acrivastine",
  "Acyclovir (Systemic)",
  "Acyclovir-Valacyclovir",
  "Adagrasib",
  "Adalimumab",
  "Adefovir",
  "Adenosine",
  "Ado-Trastuzumab Emtansine",
  "Aducanumab",
  "Afatinib",
  "Agalsidase Alfa",
  "Agalsidase Beta",
  "Agents That Do Not Require Patiromer Dose Separation",
  "Agents With Seizure Threshold Lowering Potential",
  "Agents that Undergo Intracellular Phosphorylation",
  "Agents to Treat Airway Disease",
  "Agents with Antiplatelet Effects",
  "Agents with Blood Glucose Lowering Effects",
  "Agents with Clinically Relevant Anticholinergic Effects",
  "Agomelatine",
  "Ajmaline",
  "Albendazole",
  "Albuterol",
  "Alcohol (Ethyl)",
  "Aldesleukin",
  "Alectinib",
  "Alemtuzumab",
  "Alendronate",
  "Alfacalcidol",
  "Alfuzosin",
  "Alirocumab",
  "Aliskiren",
  "Alitretinoin (Systemic)",
  "Alizapride",
  "Alkalinizing Agents",
  "Allopurinol",
  "Almotriptan",
  "Aloe",
  "Alosetron",
  "Alpelisib",
  "Alpha-/Beta-Agonists",
  "Alpha-/Beta-Agonists (Direct-Acting)",
  "Alpha-/Beta-Agonists (Indirect-Acting)",
  "Alpha-Glucosidase Inhibitors",
  "Alpha-Lipoic Acid",
  "Alpha1-Agonists",
  "Alpha1-Blockers",
  "Alpha1-Blockers (Nonselective)",
  "Alpha1-Blockers (Uroselective)",
  "Alpha2-Agonists",
  "Alpha2-Agonists (Ophthalmic)",
  "Alprostadil",
  "Alteplase",
  "Aluminum Hydroxide",
  "Aluminum-Containing Products",
  "Alvimopan",
  "AmLODIPine",
  "Amantadine",
  "Ambrisentan",
  "Amezinium",
  "Amifampridine",
  "Amifostine",
  "Amikacin Liposome (Oral Inhalation)",
  "Aminoglycosides",
  "Aminolevulinic Acid (Systemic)",
  "Aminolevulinic Acid (Topical)",
  "Aminophylline",
  "Aminoquinolines (Antimalarial)",
  "Aminosalicylic Acid",
  "Amiodarone",
  "Amisulpride (Injection)",
  "Amisulpride (Oral)",
  "Amitriptyline",
  "Amitriptylinoxide",
  "Ammonium Chloride",
  "Amodiaquine",
  "Amoxapine",
  "Amoxicillin",
  "Amphetamines",
  "Amphotericin B",
  "Ampicillin",
  "Amyl Nitrite",
  "Anacaulase",
  "Anagliptin",
  "Anagrelide",
  "Anastrozole",
  "Andexanet Alfa (Coagulation Factor Xa [Recombinant], Inactivated)",
  "Androgen Deprivation Therapy Agents",
  "Androgens",
  "Angiogenesis Inhibitors (Systemic)",
  "Angiotensin II",
  "Angiotensin II Receptor Blockers",
  "Angiotensin-Converting Enzyme Inhibitors",
  "Anifrolumab",
  "Antacids",
  "Antagonist) / Buprenorphine",
  "Antagonist) / Levomethadone",
  "Antagonist) / Opioid Agonists",
  "Anthracyclines",
  "Anthrax Immune Globulin (Human)",
  "Anti-CD20 B-Cell Depleting Therapies",
  "Anti-Parkinson Agents (Dopamine Agonist)",
  "Anti-Parkinson Agents (Monoamine Oxidase Inhibitor)",
  "Anti-TNF Agents",
  "Antiandrogens",
  "Antianxiety Agents",
  "Antiarrhythmic Agents (Class III)",
  "Antibiotics",
  "Anticholinergic Anti-Parkinsonian Agents",
  "Anticoagulants",
  "Anticoagulants (Inhibitors of Factor Xa)",
  "Anticoagulants (Miscellaneous Agents)",
  "Antidepressants",
  "Antidepressants with Antiplatelet Effects",
  "Antidiabetic Agents",
  "Antiemetics (5HT3 Antagonists)",
  "Antifungal Agents (Azole Derivatives, Systemic)",
  "Antifungal Agents (Systemic and Oral [Non-Absorbable])",
  "Antifungal Agents (Vaginal)",
  "Antihepaciviral Combination Products",
  "Antiherpetic Antivirals",
  "Antihistamines",
  "Antihistamines, First Generation",
  "Antihypertensive Agents",
  "Antimalarial Agents",
  "Antineoplastic Agents",
  "Antineoplastic Agents (Vinca Alkaloids)",
  "Antiplatelet Agents (P2Y12 Inhibitors)",
  "Antipsychotic Agents",
  "Antipsychotic Agents (First Generation [Typical])",
  "Antipsychotic Agents (Phenothiazines)",
  "Antipsychotic Agents (Second Generation [Atypical])",
  "Antiretroviral Agents",
  "Antiseizure Agents",
  "Antiseizure Agents (Sodium Channel Blockers)",
  "Antithrombin",
  "Antithymocyte Globulin (Equine)",
  "Antithyroid Agents",
  "Antiviral Agents (Influenza A and B)",
  "Apalutamide",
  "Apixaban",
  "Apomorphine",
  "Apples",
  "Apraclonidine",
  "Apremilast",
  "Aprepitant",
  "Aprotinin",
  "Arbekacin",
  "Arginine",
  "Arimoclomol",
  "Armodafinil",
  "Aromatase Inhibitors",
  "Arsenic Trioxide",
  "Artemether and Lumefantrine",
  "Artesunate",
  "Articaine",
  "Asciminib",
  "Ascorbic Acid",
  "Asenapine",
  "Asparaginase Products",
  "Aspirin",
  "Ataluren",
  "Atazanavir",
  "Atenolol",
  "Atidarsagene Autotemcel",
  "Atogepant",
  "Atomoxetine",
  "Atorvastatin",
  "Atosiban",
  "Atovaquone",
  "Atrasentan",
  "Atropine (Ophthalmic)",
  "Atropine (Systemic)",
  "Avacopan",
  "Avanafil",
  "Avapritinib",
  "Avatrombopag",
  "Avibactam",
  "Avocado",
  "Axitinib",
  "AzaTHIOprine",
  "Azelastine (Nasal)",
  "Azilsartan",
  "Azithromycin (Systemic)",
  "Azosemide",
  "BCG Products",
  "BCRP/ABCG2 Inducers",
  "BCRP/ABCG2 Inhibitors",
  "BCRP/ABCG2 Substrates (Clinically Relevant with Inhibitors)",
  "BUPivacaine",
  "BUPivacaine (Liposomal)",
  "Bacampicillin",
  "Bacillus Calmette Guerin (BCG) (Intravesical)",
  "Bacillus Calmette Guerin (BCG) (Percutaneous)",
  "Bacillus clausii",
  "Bacitracin (Systemic)",
  "Baclofen",
  "Baloxavir Marboxil",
  "Bambuterol",
  "Barbiturates",
  "Baricitinib",
  "Barnidipine",
  "Bazedoxifene",
  "Beclomethasone (Oral Inhalation)",
  "Beclomethasone (Systemic)",
  "Bedaquiline",
  "Belimumab",
  "Belinostat",
  "Belotecan",
  "Belumosudil",
  "Belzutifan",
  "Bemiparin",
  "Bempedoic Acid",
  "Bendamustine",
  "Benidipine",
  "Benoxinate",
  "Benperidol",
  "Benzamide Derivatives",
  "Benzbromarone",
  "Benzgalantamine-Galantamine",
  "Benzhydrocodone",
  "Benzodiazepines",
  "Benzodiazepines (metabolized by glucuronidation)",
  "Benzoyl Peroxide",
  "Benztropine",
  "Benzylpenicilloyl Polylysine",
  "Berberine-Containing Products",
  "Berotralstat",
  "Beta-Acetyldigoxin",
  "Beta-Blockers",
  "Beta-Blockers (Beta1 Selective)",
  "Beta-Blockers (Nonselective)",
  "Beta-Blockers (with Alpha-Blocking Properties)",
  "Beta2-Agonists",
  "Beta2-Agonists (Long-Acting)",
  "Beta2-Agonists (Short-Acting)",
  "Betahistine",
  "Betalactamase Inhibitors",
  "Betamethasone (Nasal)",
  "Betamethasone (Ophthalmic)",
  "Betamethasone (Systemic)",
  "Betamethasone (Topical)",
  "Betibeglogene Autotemcel",
  "Bevacizumab",
  "Bexagliflozin",
  "Bexarotene (Systemic)",
  "Bezafibrate",
  "Bicalutamide",
  "Bictegravir",
  "Bifonazole",
  "Bilastine",
  "Bile Acid Sequestrants",
  "Bimatoprost",
  "Bimekizumab",
  "Biologic Anti-Psoriasis Agents",
  "Biologic Disease-Modifying Antirheumatic Drugs",
  "Biperiden",
  "Bisacodyl",
  "Bismuth Subcitrate",
  "Bismuth Subsalicylate",
  "Bismuth-Containing Compounds",
  "Bisoprolol",
  "Bisphosphonate Derivatives",
  "Bitter Orange",
  "Bleomycin",
  "Blonanserin",
  "Blood Pressure Lowering Agents",
  "Boldo",
  "Bornaprine",
  "Bortezomib",
  "Bosentan",
  "Bosutinib",
  "Botulinum Toxin-Containing Products",
  "Bradycardia-Causing Agents",
  "Brensocatib",
  "Brentuximab Vedotin",
  "Bretylium",
  "Brexanolone",
  "Brexpiprazole",
  "Brigatinib",
  "Brimonidine (Ophthalmic)",
  "Brimonidine (Topical)",
  "Brincidofovir",
  "Brivaracetam",
  "Brivudine",
  "Broccoli",
  "Bromazepam",
  "Bromocriptine",
  "Bromopride",
  "Bromperidol",
  "Brompheniramine",
  "Broom",
  "Brotizolam",
  "BuPROPion",
  "Buclizine",
  "Budesonide (Nasal)",
  "Budesonide (Oral Inhalation)",
  "Budesonide (Systemic)",
  "Budesonide (Topical)",
  "Bulevirtide",
  "Buprenorphine",
  "Burosumab",
  "BusPIRone",
  "Busulfan",
  "Butamirate",
  "Butorphanol",
  "C / Y and W-135) Conjugate Vaccine / Tetanus Toxoids Vaccines",
  "C1 Inhibitors",
  "CAR-T Cell Immunotherapy",
  "CARBOplatin",
  "CISplatin",
  "CNS Depressants",
  "CNS Stimulants",
  "COMT Inhibitors",
  "COMT Substrates",
  "COVID-19 Vaccine (Inactivated Virus)",
  "COVID-19 Vaccine (Subunit)",
  "COVID-19 Vaccine (mRNA)",
  "COVID-19 Vaccines",
  "CYP Substrates (Narrow Therapeutic Index/Sensitive with Inducers)",
  "CYP Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP1A2 Inducers (Moderate)",
  "CYP1A2 Inducers (Weak)",
  "CYP1A2 Inhibitors (Moderate)",
  "CYP1A2 Inhibitors (Strong)",
  "CYP1A2 Inhibitors (Weak)",
  "CYP1A2 Substrates (High risk with Inducers)",
  "CYP1A2 Substrates (High risk with Inhibitors)",
  "CYP1A2 Substrates (Narrow Therapeutic Index/Sensitive with Inducers)",
  "CYP1A2 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP2B6 Inducers (Moderate)",
  "CYP2B6 Inducers (Weak)",
  "CYP2B6 Inhibitors (Weak)",
  "CYP2B6 Substrates (High risk with Inducers)",
  "CYP2B6 Substrates (High risk with Inhibitors)",
  "CYP2B6 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP2C19 Inducers (Moderate)",
  "CYP2C19 Inducers (Strong)",
  "CYP2C19 Inducers (Weak)",
  "CYP2C19 Inhibitors (Moderate)",
  "CYP2C19 Inhibitors (Strong)",
  "CYP2C19 Inhibitors (Weak)",
  "CYP2C19 Substrates (High risk with Inducers)",
  "CYP2C19 Substrates (High risk with Inhibitors)",
  "CYP2C19 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP2C8 Inducers (Moderate)",
  "CYP2C8 Inhibitors (Moderate)",
  "CYP2C8 Inhibitors (Strong)",
  "CYP2C8 Inhibitors (Weak)",
  "CYP2C8 Substrates (High Risk with Inhibitors or Inducers)",
  "CYP2C8 Substrates (High risk with Inhibitors)",
  "CYP2C8 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP2C9 Inducers (Moderate)",
  "CYP2C9 Inducers (Weak)",
  "CYP2C9 Inhibitors (Moderate)",
  "CYP2C9 Inhibitors (Weak)",
  "CYP2C9 Substrates (High Risk with Inhibitors or Inducers)",
  "CYP2C9 Substrates (High risk with Inducers)",
  "CYP2C9 Substrates (High risk with Inhibitors)",
  "CYP2C9 Substrates (Narrow Therapeutic Index/Sensitive with Inducers)",
  "CYP2C9 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "CYP2D6 Inhibitors (Moderate)",
  "CYP2D6 Inhibitors (Strong)",
  "CYP2D6 Inhibitors (Weak)",
  "CYP2D6 Substrates (High risk with Inhibitors)",
  "CYP2D6 Substrates (Narrow Therapeutic Index/Sensitive)",
  "CYP2E1 Inhibitors (Moderate)",
  "CYP2E1 Inhibitors (Strong)",
  "CYP2E1 Inhibitors (Weak)",
  "CYP3A4 Inducers (Moderate)",
  "CYP3A4 Inducers (Strong)",
  "CYP3A4 Inducers (Weak)",
  "CYP3A4 Inhibitors (Moderate)",
  "CYP3A4 Inhibitors (Strong)",
  "CYP3A4 Inhibitors (Weak)",
  "CYP3A4 Substrates (High risk with Inhibitors)",
  "CYP3A4 Substrates (Narrow Therapeutic Index/Sensitive with Inducers)",
  "CYP3A4 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "Cabazitaxel",
  "Cabergoline",
  "Cabotegravir",
  "Cabozantinib",
  "Cafedrine",
  "Caffeine and Caffeine Containing Products",
  "Calcifediol",
  "Calcimimetic Agents",
  "Calcitonin",
  "Calcitriol (Systemic)",
  "Calcium Acetate",
  "Calcium Carbonate",
  "Calcium Channel Blockers",
  "Calcium Channel Blockers (Dihydropyridine)",
  "Calcium Channel Blockers (Nondihydropyridine)",
  "Calcium Polystyrene Sulfonate",
  "Calcium Salts",
  "Calcium Salts (Intravenous)",
  "Canagliflozin",
  "Canakinumab",
  "Candesartan",
  "Cangrelor",
  "Cannabidiol",
  "Cannabinoid-Containing Products",
  "Cannabis",
  "Capecitabine",
  "Capivasertib",
  "Caplacizumab",
  "Capmatinib",
  "Capreomycin",
  "Capsaicin",
  "Captopril",
  "CarBAMazepine",
  "Carbachol",
  "Carbapenems",
  "Carbetocin",
  "Carbidopa",
  "Carbimazole",
  "Carbinoxamine",
  "Carbonic Anhydrase Inhibitors",
  "Carboprost Tromethamine",
  "Cardiac Glycosides",
  "Carfilzomib",
  "Cariprazine",
  "Carisoprodol",
  "Carmustine",
  "Carvedilol",
  "Caspofungin",
  "CeFAZolin",
  "Cedazuridine",
  "CefTAZidime",
  "CefTRIAXone",
  "Cefaclor",
  "Cefazedone",
  "Cefditoren",
  "Cefiderocol",
  "Cefmetazole",
  "Cefoperazone",
  "Cefotaxime",
  "Cefotiam",
  "Cefpirome",
  "Cefpodoxime",
  "Ceftibuten",
  "Ceftizoxime",
  "Ceftobiprole Medocaril",
  "Cefuroxime",
  "Celecoxib",
  "Celery",
  "Celiprolol",
  "Cellulose and Citric Acid",
  "Cenobamate",
  "Cephalexin",
  "Cephaloridine",
  "Cephalosporins",
  "Cephalosporins (N-methylthiotetrazole [NMTT] Side Chain Containing)",
  "Cephalothin",
  "Cephradine",
  "Cerebrolysin",
  "Ceritinib",
  "Certoparin",
  "Cetirizine (Systemic)",
  "Chamomile",
  "Charcoal, Activated",
  "Chenodiol",
  "Chikungunya Vaccine (Live)",
  "Chitosan",
  "Chloral Hydrate/Chloral Betaine",
  "Chloramphenicol (Ophthalmic)",
  "Chloramphenicol (Systemic)",
  "ChlordiazePOXIDE",
  "Chlormethiazole",
  "Chloroprocaine (Systemic)",
  "Chloroquine",
  "Chlorphenesin Carbamate",
  "Chlorpheniramine",
  "ChlorproMAZINE",
  "ChlorproPAMIDE",
  "Chlorprothixene",
  "Chlorthalidone",
  "Chlorzoxazone",
  "Cholera Vaccine",
  "Cholestyramine Resin",
  "Cholic Acid",
  "Choline C 11",
  "Cholinergic Agonists",
  "Chondroitin Sulfate",
  "Chromium",
  "Ciclesonide (Oral Inhalation)",
  "Cidofovir",
  "Cilnidipine",
  "Cilostazol",
  "Cimetidine",
  "Cimetropium",
  "Cinacalcet",
  "Cinnamon",
  "Cinnarizine",
  "Ciprofibrate",
  "Ciprofloxacin (Ophthalmic)",
  "Ciprofloxacin (Systemic)",
  "Cisapride",
  "Citalopram",
  "Citric Acid Derivatives",
  "Cladribine",
  "Clarithromycin",
  "Class IA Antiarrhythmics",
  "Clemastine",
  "Clindamycin (Systemic)",
  "Clindamycin (Topical)",
  "CloBAZam",
  "CloNIDine",
  "CloZAPine",
  "Clobetasone",
  "Clofarabine",
  "Clofazimine",
  "ClomiPHENE",
  "ClomiPRAMINE",
  "ClonazePAM",
  "Clopidogrel",
  "Clorazepate",
  "Clothiapine",
  "Cloxacillin",
  "Cobicistat",
  "Cobimetinib",
  "Cocaine (Topical)",
  "Coccidioides immitis Skin Test",
  "Codeine",
  "Coenzyme Q-10",
  "Cola-Containing Drinks",
  "Colchicine",
  "Colesevelam",
  "Colestipol",
  "Colistimethate",
  "Collagenase (Systemic)",
  "Conivaptan",
  "Copanlisib",
  "Copper Cu 64 Dotatate",
  "Corifollitropin Alfa",
  "Corticosteroids",
  "Corticosteroids (Nasal)",
  "Corticosteroids (Ophthalmic)",
  "Corticosteroids (Orally Inhaled)",
  "Corticosteroids (Systemic)",
  "Corticotropin",
  "Cortisone",
  "Cosyntropin",
  "Cranberry",
  "Crinecerfont",
  "Crisaborole",
  "Crizotinib",
  "Cyclizine",
  "CycloPHOSphamide",
  "CycloSERINE",
  "CycloSPORINE (Systemic)",
  "Cyclobenzaprine",
  "Cyclopentolate",
  "Cyproheptadine",
  "Cyproterone",
  "Cysteamine (Systemic)",
  "Cytidine Deaminase Substrates",
  "DAPTOmycin",
  "DOBUTamine",
  "DOCEtaxel",
  "DOPamine",
  "DOXOrubicin (Conventional)",
  "DOXOrubicin (Liposomal)",
  "DULoxetine",
  "Dabigatran Etexilate",
  "Dabrafenib",
  "Dacarbazine",
  "Daclatasvir",
  "Dacomitinib",
  "Dalfampridine",
  "Danazol",
  "Dandelion",
  "Danicopan",
  "Danshen",
  "Dantrolene",
  "Dapagliflozin",
  "Dapoxetine",
  "Daprodustat",
  "Dapsone (Systemic)",
  "Dapsone (Topical)",
  "Darbepoetin Alfa",
  "Daridorexant",
  "Darifenacin",
  "Darolutamide",
  "Darunavir",
  "Dasabuvir",
  "Dasatinib",
  "Decongestants",
  "Defactinib",
  "Deferasirox",
  "Deferiprone",
  "Deferoxamine",
  "Defibrotide",
  "Deflazacort",
  "Delamanid",
  "Delgocitinib",
  "Demeclocycline",
  "Dengue Tetravalent Vaccine (Live)",
  "Denosumab",
  "Deoxycholic Acid",
  "Dermal Fillers",
  "Desipramine",
  "Desirudin",
  "Desloratadine",
  "Desmopressin",
  "Desvenlafaxine",
  "Deucravacitinib",
  "Deuruxolitinib",
  "Deutetrabenazine",
  "DexAMETHasone (Ophthalmic)",
  "DexAMETHasone (Systemic)",
  "Dexamethasone (Topical)",
  "Dexbrompheniramine",
  "Dexchlorpheniramine",
  "Dexibuprofen",
  "Dexketoprofen",
  "Dexlansoprazole",
  "DexmedeTOMIDine",
  "Dexmethylphenidate",
  "Dexmethylphenidate-Methylphenidate",
  "Dexrazoxane",
  "Dextran",
  "Dextromethorphan",
  "Diacerein",
  "Diamorphine",
  "DiazePAM",
  "Diazoxide (Immediate Release)",
  "Diazoxide Choline (Extended Release)",
  "Dichlorphenamide",
  "Diclofenac (Systemic)",
  "Dicloxacillin",
  "Dicyclomine",
  "Dienogest",
  "Diethylamine Salicylate",
  "Diethylpropion",
  "Diethylstilbestrol",
  "Difelikefalin",
  "Difenoxin",
  "Diflunisal",
  "Digitoxin",
  "Digoxin",
  "Dihydralazine",
  "Dihydrocodeine",
  "Dihydroergotamine",
  "Dihydrofolate Reductase (DHFR) Inhibitors",
  "DilTIAZem",
  "Dimenhydrinate",
  "Dimercaprol",
  "Dimethicone (Systemic)",
  "Dimethindene (Systemic)",
  "Dimethindene (Topical)",
  "Dimethyl Fumarate",
  "Dinoprostone",
  "Dinutuximab Beta",
  "Diosmin",
  "Dipeptidyl Peptidase-IV Inhibitors",
  "DiphenhydrAMINE (Systemic)",
  "Diphenoxylate",
  "Dipyridamole",
  "Dipyrone",
  "Direct Acting Antiviral Agents (HCV)",
  "Direct Oral Anticoagulants (DOACs)",
  "Disopyramide",
  "Distigmine",
  "Disulfiram",
  "Diuretics",
  "Dofetilide",
  "Dolasetron",
  "Dolutegravir",
  "Domperidone",
  "Donanemab",
  "Donepezil",
  "Dong Quai",
  "Doravirine",
  "Dordaviprone",
  "Dothiepin",
  "Doxapram",
  "Doxazosin",
  "Doxepin (Systemic)",
  "Doxepin (Topical)",
  "Doxepin-Containing Products",
  "Doxercalciferol",
  "Doxofylline",
  "Doxycycline",
  "Doxylamine",
  "DroNABinol",
  "DroPERidol",
  "Dronedarone",
  "Drospirenone-Containing Products",
  "Droxidopa",
  "Drugs Suspected of Causing Diabetes Insipidus",
  "Drugs Suspected of Causing SIADH",
  "Drugs that Affect Gallbladder Function",
  "Dupilumab",
  "Dutasteride",
  "Duvelisib",
  "Dydrogesterone",
  "Dyphylline",
  "EPHEDrine (Nasal)",
  "EPHEDrine (Systemic)",
  "EPINEPHrine (Oral Inhalation)",
  "EPINEPHrine (Systemic)",
  "Ebastine",
  "Echinacea",
  "Echothiophate Iodide",
  "Econazole",
  "Edetate CALCIUM Disodium",
  "Edoxaban",
  "Efavirenz",
  "Efgartigimod Alfa",
  "Efonidipine",
  "Elacestrant",
  "Elafibranor",
  "Elagolix",
  "Elagolix, Estradiol, and Norethindrone",
  "Elbasvir and Grazoprevir",
  "Eletriptan",
  "Elexacaftor, Tezacaftor, and Ivacaftor",
  "Eliglustat",
  "Elinzanetant",
  "Elivaldogene Autotemcel",
  "Elobixibat",
  "Elranatamab",
  "Eltrombopag",
  "Eluxadoline",
  "Elvitegravir",
  "Emedastine (Systemic)",
  "Empagliflozin",
  "Emtricitabine",
  "Enalapril (Oral)",
  "Enasidenib",
  "Encorafenib",
  "Enfortumab Vedotin",
  "Enfuvirtide",
  "Enoxaparin",
  "Enoximone",
  "Ensartinib",
  "Ensifentrine",
  "Entacapone",
  "Entrectinib",
  "Enzalutamide",
  "Epcoritamab",
  "Ephedra",
  "EpiRUBicin",
  "Epinephrine (Racemic)",
  "Eplerenone",
  "Epoprostenol",
  "Eravacycline",
  "Erdafitinib",
  "Ergoloid Mesylates",
  "Ergonovine",
  "Ergot Derivatives",
  "Ergot Derivatives (Vasoconstrictive CYP3A4 Substrates)",
  "Erlotinib",
  "Ertapenem",
  "Ertugliflozin",
  "Erythromycin (Ophthalmic)",
  "Erythromycin (Systemic)",
  "Erythropoiesis-Stimulating Agents",
  "Escitalopram",
  "Esketamine (Injection)",
  "Esketamine (Nasal)",
  "Eslicarbazepine",
  "Esmolol",
  "Esomeprazole",
  "Estazolam",
  "Estramustine",
  "Estriol (Systemic)",
  "Estrogen Derivatives",
  "Estrogen Derivatives (Contraceptive)",
  "Estrogen Receptor Antagonists",
  "Eszopiclone",
  "Etamsylate",
  "Etanercept",
  "Etelcalcetide",
  "Ethacrynic Acid",
  "Ethambutol",
  "Ethinyl Estradiol-Containing Products",
  "Ethionamide",
  "Ethosuximide",
  "Etilefrine",
  "Etizolam",
  "Etofenamate",
  "Etofylline",
  "Etoposide",
  "Etoposide Phosphate",
  "Etoricoxib",
  "Etrasimod",
  "Etravirine",
  "Eurycoma Longifolia",
  "Evening Primrose",
  "Everolimus",
  "Evogliptin",
  "Evolocumab",
  "Exagamglogene Autotemcel",
  "Exemestane",
  "Exenatide",
  "Ezetimibe",
  "FLUoxetine",
  "Factor X (Human)",
  "Fam-Trastuzumab Deruxtecan",
  "Famciclovir",
  "Famotidine",
  "Favipiravir",
  "Fc Receptor-Binding Agents",
  "Febuxostat",
  "Fecal Microbiota (Live) (Oral)",
  "Fecal Microbiota (Live) (Rectal)",
  "Fedratinib",
  "Felbamate",
  "Felodipine",
  "Fenfluramine",
  "Fenofibrate and Derivatives",
  "Fenoprofen",
  "Fenoterol",
  "FentaNYL",
  "Fenugreek",
  "Ferric Gluconate",
  "Ferric Hydroxide Polymaltose Complex",
  "Fesoterodine",
  "Fexinidazole",
  "Fexofenadine",
  "Fexuprazan",
  "Fezolinetant",
  "Fibric Acid Derivatives",
  "Filgotinib",
  "Filgrastim",
  "Fimasartan",
  "Finasteride",
  "Finerenone",
  "Fingolimod",
  "Flaxseed",
  "Flecainide",
  "Flibanserin",
  "Flotufolastat F18",
  "FluPHENAZine",
  "Flucloxacillin",
  "Fluconazole",
  "Flucytosine",
  "Fludeoxyglucose F 18",
  "Fludrocortisone",
  "Flunarizine",
  "Flunitrazepam",
  "Fluoride",
  "Fluorodopa F18",
  "Fluoroestradiol F18",
  "Fluorouracil (Systemic)",
  "Fluorouracil Products",
  "Flupentixol",
  "Flurazepam",
  "Flurbiprofen (Systemic)",
  "Fluticasone (Nasal)",
  "Fluticasone (Oral Inhalation)",
  "Fluticasone (Topical)",
  "Fluvastatin",
  "FluvoxaMINE",
  "Folic Acid",
  "Fondaparinux",
  "Formoterol",
  "Fosamprenavir",
  "Fosaprepitant",
  "Foscarbidopa",
  "Foscarnet",
  "Fosfomycin",
  "Fosinopril",
  "Foslevodopa",
  "Fosnetupitant",
  "Fosphenytoin",
  "Fosphenytoin-Phenytoin",
  "Fostamatinib",
  "Fostemsavir",
  "Fotemustine",
  "Frankincense, Indian",
  "Frovatriptan",
  "Fruit Acids",
  "Fruquintinib",
  "Furosemide",
  "Fusidic Acid (Systemic)",
  "Futibatinib",
  "Gabapentin (Immediate Release)",
  "Gabapentin Enacarbil (Extended Release)",
  "Gadobenate Dimeglumine",
  "Gallium Ga 68 Dotatate",
  "Gallium Ga 68 Dotatoc",
  "Gallium Ga 68 PSMA-11",
  "Ganaxolone",
  "Ganciclovir-Valganciclovir",
  "Garcinia",
  "Garlic",
  "Gastrointestinal Agents (Prokinetic)",
  "Gefitinib",
  "Gelatin (Succinylated)",
  "Gemcitabine (Systemic)",
  "Gemeprost",
  "Gemfibrozil",
  "Gemifloxacin",
  "Gemigliptin",
  "Gentamicin (Systemic)",
  "Gepirone",
  "Gepotidacin",
  "Gestrinone",
  "Gilteritinib",
  "Gimeracil",
  "Ginkgo Biloba",
  "Ginseng",
  "Ginseng (Siberian)",
  "Givinostat",
  "Glasdegib",
  "Glecaprevir and Pibrentasvir",
  "Gliclazide",
  "Glimepiride",
  "Glofitamab",
  "Glucagon",
  "Glucagon and Glucagon Analogs",
  "Glucagon-Like Peptide-1 Agonists",
  "Glucomannan",
  "Glucosamine",
  "Glutamine",
  "GlyBURIDE",
  "Glycoprotein IIb/IIIa Inhibitors",
  "Glycopyrrolate (Oral Inhalation)",
  "Glycopyrrolate (Systemic)",
  "Glycopyrronium (Topical)",
  "Goji Berry",
  "Golimumab",
  "Gossypol",
  "Granulocyte Colony-Stimulating Factors",
  "Grape Juice, Purple",
  "Grape Seed",
  "Grapefruit Juice",
  "Grass Pollen Allergen Extract (5 Grass Extract)",
  "Green Tea",
  "Griseofulvin",
  "Growth Hormone Analogs",
  "GuaiFENesin",
  "GuanFACINE",
  "Guanethidine",
  "Guar Gum (Partially Hydrolyzed)",
  "Guggul",
  "HMG-CoA Reductase Inhibitors (Statins)",
  "HYDROcodone",
  "HYDROmorphone",
  "Halofantrine",
  "Haloperidol",
  "Hawthorn",
  "Hemin",
  "Heparin",
  "Heparins (Low Molecular Weight)",
  "Herbal Products with Anticoagulant/Antiplatelet Effects",
  "Herbal Products with Blood Pressure Increasing Effects",
  "Herbal Products with Blood Pressure Lowering Effects",
  "Herbal Products with Glucose Lowering Effects",
  "Hexoprenaline",
  "Hibiscus",
  "Histamine H2 Receptor Antagonists",
  "Histone Deacetylase Inhibitors",
  "Honeybee Products",
  "Hops",
  "Hormonal Contraceptives",
  "Huperzine A",
  "Hyaluronidase",
  "HydrALAZINE",
  "HydrOXYzine",
  "HydroCHLOROthiazide",
  "Hydrocortisone (Ophthalmic)",
  "Hydrocortisone (Systemic)",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "Hyoscyamine",
  "Hyperglycemia-Associated Agents",
  "Hyperprolactinemic Agents",
  "Hypertension-Associated Agents",
  "Hypnotics (Nonbenzodiazepine)",
  "Hypoglycemia-Associated Agents",
  "Hyponatremia-Associated Agents",
  "Hypotension-Associated Agents",
  "IDArubicin",
  "ISOtretinoin (Systemic)",
  "Iboga",
  "Ibrexafungerp",
  "Ibritumomab Tiuxetan",
  "Ibrutinib",
  "Ibuprofen (Systemic)",
  "Icatibant",
  "Icosapent Ethyl",
  "Idebenone",
  "Idelalisib",
  "Ifosfamide",
  "Ilaprazole",
  "Iloperidone",
  "Imatinib",
  "Imidafenacin",
  "Imidapril",
  "Imipenem",
  "Imipramine",
  "Imlunestrant",
  "Immune Checkpoint Inhibitors (Anti-PD-1, -PD-L1, and -CTLA4 Therapies)",
  "Immune Globulin",
  "Immune Globulins",
  "Immunosuppressants (Cytotoxic Chemotherapy)",
  "Immunosuppressants (Miscellaneous Oncologic Agents)",
  "Immunosuppressants (Therapeutic Immunosuppressant Agents)",
  "InFLIXimab",
  "Indacaterol",
  "Indium 111 Capromab Pendetide",
  "Indomethacin (Systemic)",
  "Indoramin",
  "Inducers of CYP3A4 (Moderate) and P-glycoprotein",
  "Inducers of CYP3A4 (Strong) and P-glycoprotein",
  "Inducers of Drug Clearance",
  "Inebilizumab",
  "Influenza Virus Vaccine (Inactivated)",
  "Influenza Virus Vaccine (Live/Attenuated)",
  "Influenza Virus Vaccines",
  "Inhalational Anesthetics",
  "Inhaled Anticholinergic Agents",
  "Inhibitors of CYP3A4 (Moderate) and P-glycoprotein",
  "Inhibitors of CYP3A4 (Strong) and BCRP",
  "Inhibitors of CYP3A4 (Strong) and P-glycoprotein",
  "Inhibitors of CYP3A4 and CYP2C9",
  "Inhibitors of Equilibrative Nucleoside (ENT1) and Concentrative Nucleoside (CNT3) Transporters",
  "Inhibitors of the Proton Pump (PPIs and PCABs)",
  "Inotersen",
  "Inotuzumab Ozogamicin",
  "Insulin",
  "Interferons",
  "Interferons (Alfa)",
  "Interleukin-6 (IL-6) Inhibiting Therapies",
  "Iobenguane Radiopharmaceutical Products",
  "Iodinated Contrast Agents",
  "Ioflupane I 123",
  "Iohexol",
  "Iomeprol",
  "Iopamidol",
  "Ipragliflozin",
  "Ipratropium (Nasal)",
  "Ipratropium (Oral Inhalation)",
  "Iptacopan",
  "Irbesartan",
  "Irinotecan Products",
  "Iron Dextran Complex",
  "Iron Preparations",
  "Isavuconazonium Sulfate",
  "Isocarboxazid",
  "Isoconazole",
  "Isoflurane",
  "Isoniazid",
  "Isoproterenol",
  "Isradipine",
  "Istradefylline",
  "Itopride",
  "Itraconazole",
  "Ivabradine",
  "Ivacaftor",
  "Ivermectin (Systemic)",
  "Ivosidenib",
  "Ixabepilone",
  "Ixazomib",
  "Janus Kinase (JAK) Inhibitors",
  "Japanese Encephalitis Virus Vaccine (Live/Attenuated)",
  "Kanamycin",
  "Kaolin",
  "Kava Kava",
  "Ketamine",
  "Ketoconazole (Systemic)",
  "Ketoprofen",
  "Ketorolac (Nasal)",
  "Ketorolac (Systemic)",
  "Ketotifen (Systemic)",
  "Khat",
  "Kratom",
  "L-Theanine",
  "LORazepam",
  "Labetalol",
  "Lacidipine",
  "Lacosamide",
  "Lactitol",
  "Lactobacillus and Estriol",
  "Lactulose",
  "LamiVUDine",
  "LamoTRIgine",
  "Landiolol",
  "Lansoprazole",
  "Lanthanum",
  "Lapatinib",
  "Larotrectinib",
  "Lasmiditan",
  "Latanoprost",
  "Latanoprostene Bunod",
  "Laxatives",
  "Laxatives (Stimulant)",
  "Lazertinib",
  "Lebrikizumab",
  "Lecanemab",
  "Ledipasvir",
  "Lefamulin",
  "Lefamulin (Intravenous)",
  "Leflunomide",
  "Lemborexant",
  "Lenacapavir",
  "Lenalidomide",
  "Leniolisib",
  "Lenograstim",
  "Lentinan",
  "Lenvatinib",
  "Lercanidipine",
  "Letermovir",
  "Letrozole",
  "Leucovorin/Levoleucovorin",
  "LevETIRAcetam",
  "LevOCARNitine",
  "Levacetylleucine",
  "Levamisole",
  "Levamlodipine",
  "LevoFLOXacin (Systemic)",
  "Levobupivacaine",
  "Levocetirizine",
  "Levodopa (Oral)",
  "Levodopa-Foslevodopa",
  "Levodropropizine",
  "Levofloxacin-Containing Products (Systemic)",
  "Levoketoconazole",
  "Levomethadone",
  "Levomilnacipran",
  "Levonadifloxacin",
  "Levonorgestrel (IUD)",
  "Levonorgestrel (Systemic)",
  "Levosulpiride",
  "Levothyroxine",
  "Licorice",
  "Lidocaine (Systemic)",
  "Lidocaine (Topical)",
  "Limaprost",
  "LinaGLIPtin",
  "Lincosamide Antibiotics",
  "Lindane",
  "Linezolid",
  "Linvoseltamab",
  "Linzagolix",
  "Lipegfilgrastim",
  "Lipid Emulsion (Fish Oil Based)",
  "Lipid Emulsion (Fish Oil and Plant Based)",
  "Liraglutide",
  "Lisinopril",
  "Lisuride",
  "Lithium",
  "Lixisenatide",
  "Lobeglitazone",
  "Local Anesthetics",
  "Lofepramine",
  "Lofexidine",
  "Lomitapide",
  "Lomustine",
  "Lonafarnib",
  "Long-acting muscarinic antagonists (LAMAs)",
  "Loop Diuretics",
  "Loperamide",
  "Lopinavir",
  "Loratadine",
  "Lorlatinib",
  "Lormetazepam",
  "Lornoxicam",
  "Losartan",
  "Lovastatin",
  "Lovotibeglogene Autotemcel",
  "Loxapine",
  "Lubiprostone",
  "Lumacaftor and Ivacaftor",
  "Lumateperone",
  "Lurasidone",
  "Lurbinectedin",
  "Luteinizing Hormone-Releasing Hormone Analogs",
  "Lutetium Lu 177 Dotatate",
  "Lycopene",
  "Lysozyme",
  "MATE1/2-K Inhibitors",
  "MATE1/2-K Substrates (Clinically Relevant with Inhibitors)",
  "MRP2 Inhibitors",
  "Macimorelin",
  "Macitentan",
  "Macrolide Antibiotics",
  "Magnesium Dimecrotate",
  "Magnesium Salts",
  "Magnesium Sulfate",
  "Maitake",
  "Manidipine",
  "Mannitol (Systemic)",
  "Maralixibat",
  "Maraviroc",
  "Margetuximab",
  "Maribavir",
  "Mavacamten",
  "Mavorixafor",
  "Mebendazole",
  "Mecamylamine",
  "Meclizine",
  "Meclofenamate",
  "MedroxyPROGESTERone",
  "Mefenamic Acid",
  "Mefloquine",
  "Megestrol",
  "Meglitinides",
  "Meglumine Antimoniate",
  "Melatonin",
  "Melitracen",
  "Meloxicam",
  "Melperone",
  "Melphalan",
  "Memantine",
  "Menadiol Diphosphate",
  "Menatetrenone",
  "Meningococcal (Groups A",
  "Menthol",
  "Meperidine",
  "Mepivacaine",
  "Meprobamate",
  "Meptazinol",
  "Mequitazine",
  "Mercaptopurine",
  "Meropenem",
  "Mesalamine",
  "Mesoglycan",
  "MetFORMIN",
  "Metaraminol",
  "Metaxalone",
  "Metergoline",
  "MethIMAzole",
  "Methacholine",
  "Methadone",
  "Methemoglobinemia Associated Agents",
  "Methenamine",
  "Methocarbamol",
  "Methotrexate",
  "Methotrimeprazine",
  "Methoxsalen (Systemic)",
  "Methoxy Polyethylene Glycol-Epoetin Beta",
  "Methoxyflurane",
  "Methscopolamine",
  "Methsuximide",
  "MethylPREDNISolone (Systemic)",
  "MethylPREDNISolone (Topical)",
  "Methyldopa",
  "Methylene Blue",
  "Methylergonovine",
  "Methylnaltrexone",
  "Methylol Cephalexin",
  "Methylphenidate",
  "Methysergide",
  "Metoclopramide",
  "Metoprolol",
  "Metreleptin",
  "MetroNIDAZOLE (Systemic)",
  "MetroNIDAZOLE (Topical)",
  "MetyraPONE",
  "MetyroSINE",
  "Mexiletine",
  "MiFEPRIStone",
  "MiSOPROStol",
  "Mianserin",
  "Micafungin",
  "Miconazole (Oral)",
  "Miconazole (Topical)",
  "Midazolam",
  "Midodrine",
  "Midostaurin",
  "Mifamurtide",
  "MigALAstat",
  "Milk Thistle",
  "Milnacipran",
  "Milrinone",
  "Mineral Oil",
  "Mineralocorticoid (Aldosterone) Receptor Antagonists",
  "Minocycline (Systemic)",
  "Minocycline (Topical)",
  "Mirabegron",
  "Mirikizumab",
  "Mirodenafil",
  "Mirtazapine",
  "Mirvetuximab Soravtansine",
  "Miscellaneous Antiplatelets",
  "Mistletoe",
  "Mitapivat",
  "Mitiglinide",
  "MitoMYcin (Systemic)",
  "Mitotane",
  "Mivacurium",
  "Mizolastine",
  "Mobocertinib",
  "Moclobemide",
  "Modafinil",
  "Molindone",
  "Molsidomine",
  "Momelotinib",
  "Mometasone (Nasal)",
  "Mometasone (Oral Inhalation)",
  "Mometasone (Topical)",
  "Monoamine Oxidase Inhibitors",
  "Monoamine Oxidase Inhibitors (Antidepressant)",
  "Monoamine Oxidase Inhibitors (Type B)",
  "Montelukast",
  "Morphine (Systemic)",
  "Mosunetuzumab",
  "Moxifloxacin (Systemic)",
  "Moxonidine",
  "Multivitamins/Fluoride (with ADE)",
  "Multivitamins/Minerals (with ADEK, Folate, Iron)",
  "Multivitamins/Minerals (with AE, No Iron)",
  "Mumps- Rubella- or Varicella-Containing Live Vaccines",
  "Muscle Relaxants (Centrally Acting)",
  "Mycophenolate",
  "Myelosuppressive Agents",
  "Myrrh",
  "NIFEdipine (Systemic)",
  "NIFEdipine (Topical)",
  "NMDA Receptor Antagonists",
  "NTCP Substrates",
  "Nabilone",
  "Nadofaragene Firadenovec",
  "Nadolol",
  "Nadroparin",
  "Nafamostat",
  "Nafcillin",
  "Naftazone",
  "Naftopidil",
  "Nalbuphine",
  "Naldemedine",
  "Nalfurafine",
  "Nalmefene",
  "Naloxegol",
  "Naloxone",
  "Naltrexone",
  "Nandrolone",
  "Naproxen",
  "Natalizumab",
  "Nateglinide",
  "Nattokinase",
  "Nebivolol",
  "Nefazodone",
  "Nefopam",
  "Nelfinavir",
  "Nemolizumab",
  "Neomycin (Systemic)",
  "Neomycin (Topical)",
  "Nerandomilast",
  "Neratinib",
  "Netilmicin (Ophthalmic)",
  "Netilmicin (Systemic)",
  "Netupitant",
  "Neuromuscular-Blocking Agents",
  "Neuromuscular-Blocking Agents (Nondepolarizing)",
  "Nevirapine",
  "NiCARdipine",
  "NiMODipine",
  "Niacin",
  "Nicergoline",
  "Nicorandil",
  "Nicotine",
  "Nilotinib",
  "Nilvadipine",
  "Nintedanib",
  "Nipocalimab",
  "Niraparib",
  "Nirmatrelvir and Ritonavir",
  "Nirogacestat",
  "Nisoldipine",
  "Nitazoxanide",
  "Nitisinone",
  "Nitrazepam",
  "Nitrendipine",
  "Nitric Oxide",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Nitroprusside",
  "Nitrous Oxide",
  "Noni",
  "Nonsteroidal Anti-Inflammatory Agents",
  "Nonsteroidal Anti-Inflammatory Agents (COX-2 Selective)",
  "Nonsteroidal Anti-Inflammatory Agents (Nonselective)",
  "Nonsteroidal Anti-Inflammatory Agents (Ophthalmic)",
  "Nonsteroidal Anti-Inflammatory Agents (Topical)",
  "Norepinephrine",
  "Norfloxacin",
  "Nortriptyline",
  "Noscapine",
  "OAT1/3 Inhibitors",
  "OAT1/3 Substrates (Clinically Relevant)",
  "OATP1B1/1B3 (SLCO1B1/1B3) Inducers",
  "OATP1B1/1B3 (SLCO1B1/1B3) Inhibitors",
  "OATP1B1/1B3 (SLCO1B1/1B3) Substrates (Clinically Relevant with Inhibitors)",
  "OCT1 Substrates (Clinically Relevant with Inhibitors)",
  "OCT2 Inhibitors",
  "OCT2 Substrates (Clinically Relevant with Inhibitors)",
  "OLANZapine",
  "OXcarbazepine",
  "Obeticholic Acid",
  "Obinutuzumab",
  "Ocrelizumab",
  "Octreotide",
  "Odevixibat",
  "Ofatumumab",
  "Ofloxacin (Systemic)",
  "Olaparib",
  "Oliceridine",
  "Olmesartan",
  "Olmutinib",
  "Olodaterol",
  "Olopatadine (Nasal)",
  "Olutasidenib",
  "Omacetaxine",
  "Omadacycline",
  "Omaveloxolone",
  "Ombitasvir, Paritaprevir, Ritonavir, and Dasabuvir",
  "Ombitasvir, Paritaprevir, and Ritonavir",
  "Omega-3 Fatty Acids",
  "Omeprazole",
  "Ondansetron",
  "Opicapone",
  "Opioid Agonists",
  "Opioid Agonists (metabolized by CYP3A4 and CYP2D6)",
  "Opioid Agonists (metabolized by CYP3A4)",
  "Opioid Antagonists",
  "Opioids (Mixed Agonist",
  "Opipramol",
  "Opium",
  "Oritavancin",
  "Orlistat",
  "Ornidazole",
  "Orphenadrine",
  "Oseltamivir",
  "Osilodrostat",
  "Osimertinib",
  "Osmotic Diuretics",
  "Ospemifene",
  "Oteseconazole",
  "Oxaliplatin",
  "Oxatomide",
  "Oxitriptan",
  "Oxomemazine",
  "OxyBUTYnin",
  "OxyCODONE",
  "OxyMORphone",
  "Oxybate Salt Products",
  "Oxybate Salts (Calcium, Magnesium, Potassium, and Sodium)",
  "Oxygen",
  "Oxymetazoline (Ophthalmic)",
  "Oxymetazoline (Topical)",
  "Oxytocic Agents",
  "Oxytocin",
  "Ozagrel",
  "Ozanimod",
  "P-glycoprotein/ABCB1 Inducers",
  "P-glycoprotein/ABCB1 Inhibitors",
  "P-glycoprotein/ABCB1 Substrates (High risk with Inhibitors or Inducers)",
  "P-glycoprotein/ABCB1 Substrates (High risk with Inhibitors)",
  "P-glycoprotein/ABCB1 Substrates (Narrow Therapeutic Index/Sensitive with Inhibitors)",
  "PACLitaxel (Conventional)",
  "PACLitaxel (Protein Bound)",
  "PARoxetine",
  "PAZOPanib",
  "PEGylated Drug Products",
  "PEMEtrexed",
  "PENTobarbital",
  "PHENobarbital",
  "PONATinib",
  "PRALAtrexate",
  "Pacritinib",
  "Pafolacianine",
  "Palbociclib",
  "Palifermin",
  "Paliperidone",
  "Palopegteriparatide",
  "Palovarotene",
  "Paltusotine",
  "Pancrelipase",
  "Pancuronium",
  "Panobinostat",
  "Pantoprazole",
  "Pantothenic Acid",
  "Papaverine",
  "Papaya",
  "Paraldehyde",
  "Parathyroid Hormone",
  "Parathyroid Hormone Products",
  "Parecoxib",
  "Paricalcitol",
  "Parsley",
  "Passion Flower",
  "Patiromer",
  "Pectin",
  "Pefloxacin",
  "Pegloticase",
  "Pegvaliase",
  "Pegvisomant",
  "Pemigatinib",
  "PenicillAMINE",
  "Penicillin G",
  "Penicillin G Benzathine",
  "Penicillin G Procaine",
  "Penicillins",
  "Pentaerythritol Tetranitrate",
  "Pentamidine (Systemic)",
  "Pentosan Polysulfate Sodium",
  "Pentostatin",
  "Pentoxifylline",
  "Peppermint",
  "Perampanel",
  "Perazine",
  "Pergolide",
  "Perhexiline",
  "Periciazine",
  "Perphenazine",
  "Pexidartinib",
  "Phenelzine",
  "Phenindione",
  "Pheniramine",
  "Phenobarbital-Primidone",
  "Phentermine",
  "Phenylbutazone",
  "Phenylephrine (Ophthalmic)",
  "Phenylephrine (Systemic)",
  "Phenyltoloxamine",
  "Phenytoin",
  "Pholcodine",
  "Phosphate Binders",
  "Phosphate Supplements",
  "Phosphodiesterase 5 Inhibitors",
  "Photosensitizing Agents",
  "Phytonadione",
  "Pidotimod",
  "Piflufolastat F18",
  "Pilocarpine (Ophthalmic)",
  "Pilocarpine (Systemic)",
  "Pilsicainide",
  "Pimavanserin",
  "Pimecrolimus",
  "Pimozide",
  "Pineapple",
  "Pioglitazone",
  "Pipamperone",
  "Pipemidic Acid",
  "Piperacillin",
  "Piperaquine",
  "Piperazine",
  "Piracetam",
  "Pirfenidone",
  "Piribedil",
  "Pirtobrutinib",
  "Pitavastatin",
  "Pitolisant",
  "Pivalate-Conjugated Medications",
  "Pivmecillinam",
  "Pizotifen",
  "Platinum Derivatives",
  "Pneumococcal Vaccines",
  "Polaprezinc",
  "Polatuzumab Vedotin",
  "Poliovirus Vaccines (Live/Oral)",
  "Polyethylene Glycol 3350",
  "Polyethylene Glycol 4000",
  "Polyethylene Glycol-Electrolyte Solution",
  "Polymethylmethacrylate",
  "Polymyxin B",
  "Polyvalent Cation Containing Products",
  "Pomalidomide",
  "Pomelo",
  "Ponesimod",
  "Porfimer",
  "Posaconazole",
  "Potassium Chloride",
  "Potassium Citrate",
  "Potassium Iodate",
  "Potassium Iodide",
  "Potassium P-Aminobenzoate",
  "Potassium Phosphate",
  "Potassium Salts",
  "Potassium-Sparing Diuretics",
  "Pralsetinib",
  "Pramipexole",
  "Pramlintide",
  "Pranlukast",
  "Prasugrel",
  "Pravastatin",
  "Prazepam",
  "Praziquantel",
  "Prazosin",
  "PredniSONE",
  "PrednisoLONE (Systemic)",
  "PrednisoLONE (Topical)",
  "Pregabalin",
  "Pretomanid",
  "Prilocaine",
  "Primaquine",
  "Primidone",
  "Probenecid",
  "Probucol",
  "Procainamide",
  "Procaine",
  "Procarbazine",
  "Prochlorperazine",
  "Products Containing Ethanol",
  "Products Containing Propylene Glycol",
  "Products that Affect Growth Hormone",
  "Progesterone",
  "Progestins",
  "Progestins (Contraceptive)",
  "Proguanil",
  "Promazine",
  "Promethazine",
  "Propacetamol",
  "Propafenone",
  "Propantheline",
  "Propiverine",
  "Propofol",
  "Propranolol",
  "Propylthiouracil",
  "Prostacyclin Analogues",
  "Prostaglandins",
  "Prostaglandins (Ophthalmic)",
  "Protease Inhibitors",
  "Protein C Concentrate (Human)",
  "Prothionamide",
  "Protirelin",
  "Protriptyline",
  "Prucalopride",
  "Pseudoephedrine",
  "Psilocybin",
  "Psyllium",
  "PyRIDostigmine",
  "Pyrazinamide",
  "Pyridoxine",
  "Pyrilamine (Systemic)",
  "Pyrimethamine",
  "QT-Prolonging Inhalational Anesthetics (Moderate Risk)",
  "QT-prolonging Agents (Highest Risk)",
  "QT-prolonging Agents (Indeterminate Risk - Avoid)",
  "QT-prolonging Agents (Indeterminate Risk - Caution)",
  "QT-prolonging Agents (Moderate Risk)",
  "QT-prolonging Antidepressants (Moderate Risk)",
  "QT-prolonging Antipsychotics (Moderate Risk)",
  "QT-prolonging CYP2D6 Substrates",
  "QT-prolonging CYP3A4 Substrates",
  "QT-prolonging Class IA Antiarrhythmics (Highest Risk)",
  "QT-prolonging Class IC Antiarrhythmics (Moderate Risk)",
  "QT-prolonging Class III Antiarrhythmics (Highest Risk)",
  "QT-prolonging Kinase Inhibitors (Highest Risk)",
  "QT-prolonging Kinase Inhibitors (Moderate Risk)",
  "QT-prolonging Miscellaneous Agents (Highest Risk)",
  "QT-prolonging Miscellaneous Agents (Moderate Risk)",
  "QT-prolonging Moderate CYP3A4 Inhibitors (Moderate Risk)",
  "QT-prolonging Quinolone Antibiotics (Moderate Risk)",
  "QT-prolonging Strong CYP3A4 Inhibitors (Highest Risk)",
  "QT-prolonging Strong CYP3A4 Inhibitors (Moderate Risk)",
  "QUEtiapine",
  "Quercetin",
  "QuiNIDine",
  "QuiNINE",
  "Quinagolide",
  "Quinapril",
  "Quinidine (Non-Therapeutic)",
  "Quinolones",
  "Quinupristin and Dalfopristin",
  "Quizartinib",
  "RABEprazole",
  "ROPINIRole",
  "ROPivacaine",
  "RaNITIdine",
  "Rabies Immune Globulin (Human)",
  "Rabies Vaccine",
  "Racecadotril",
  "Radotinib",
  "Raloxifene",
  "Raltegravir",
  "Raltitrexed",
  "Ramelteon",
  "Ramipril",
  "Ramosetron",
  "Ranolazine",
  "Rasagiline",
  "Raspberry",
  "Reboxetine",
  "Red Clover",
  "Red Yeast Rice",
  "Regadenoson",
  "Regorafenib",
  "Relugolix",
  "Relugolix, Estradiol, and Norethindrone",
  "Remdesivir",
  "Remibrutinib",
  "Remifentanil",
  "Repaglinide",
  "Repotrectinib",
  "Reproterol",
  "Reserpine",
  "Resmetirom",
  "Resveratrol",
  "Retapamulin",
  "Reteplase",
  "Retinoic Acid Derivatives",
  "Revaprazan",
  "Revefenacin",
  "Reverse Transcriptase Inhibitors (Non-Nucleoside)",
  "Revumenib",
  "Rho(D) Immune Globulin",
  "Rhodiola Rosea",
  "Ribavirin (Oral Inhalation)",
  "Ribavirin (Systemic)",
  "Ribociclib",
  "RifAMPin",
  "RifAXIMin",
  "Rifabutin",
  "Rifamycin Derivatives",
  "Rifapentine",
  "Rilmenidine",
  "Rilonacept",
  "Rilpivirine",
  "Riluzole",
  "Rilzabrutinib",
  "Rimegepant",
  "Ringer's Injection (Lactated)",
  "Riociguat",
  "Ripretinib",
  "Risdiplam",
  "Risedronate",
  "RisperiDONE",
  "Ritlecitinib",
  "Ritodrine",
  "Ritonavir",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Rocuronium",
  "Roflumilast (Systemic)",
  "Roflumilast (Topical)",
  "Roflumilast-Containing Products",
  "Rolapitant",
  "RomiDEPsin",
  "Ropeginterferon Alfa-2b",
  "Rosiglitazone",
  "Rosuvastatin",
  "Rotigotine",
  "Roxadustat",
  "Roxithromycin",
  "Rozanolixizumab",
  "Rucaparib",
  "Rufinamide",
  "Rupatadine",
  "Ruxolitinib (Systemic)",
  "Ruxolitinib (Topical)",
  "SAXagliptin",
  "SITagliptin",
  "SORAfenib",
  "SUFentanil",
  "SUMAtriptan",
  "SUNItinib",
  "Saccharomyces (Yeast)",
  "Sacituzumab Govitecan",
  "Sacubitril",
  "Saffron",
  "Safinamide",
  "Salicylates",
  "Salicylates (Topical)",
  "Salicylic Acid",
  "Salmeterol",
  "Samidorphan",
  "Sanzyme",
  "Sapropterin",
  "Saquinavir",
  "Sarecycline",
  "Sargramostim",
  "Saw Palmetto",
  "Schisandra",
  "Scopolamine",
  "Seaweed Products",
  "Sebetralstat",
  "Secnidazole",
  "Secretin",
  "Seladelpar",
  "Selective Estrogen Receptor Modulators",
  "Selective Serotonin Reuptake Inhibitor",
  "Selective Serotonin Reuptake Inhibitors (Strong CYP2D6 Inhibitors)",
  "Selegiline",
  "Selenium",
  "Selexipag",
  "Selpercatinib",
  "Selumetinib",
  "Semaglutide",
  "Senna",
  "Sepiapterin",
  "Sepiapterin Reductase Inhibitors",
  "Serotonergic Agents (High Risk)",
  "Serotonergic Agents (High Risk, Miscellaneous)",
  "Serotonergic Agents (Moderate Risk)",
  "Serotonergic Agents (Moderate Risk, Miscellaneous)",
  "Serotonergic Non-Opioid CNS Depressants",
  "Serotonergic Opioids (High Risk)",
  "Serotonin 5-HT1D Receptor Agonists (Triptans)",
  "Serotonin Reuptake Inhibitor/Antagonists",
  "Serotonin/Norepinephrine Reuptake Inhibitor",
  "Sertindole",
  "Sertraline",
  "Serum Phosphate Level-Altering Agents",
  "Sevabertinib",
  "Sevelamer",
  "Sevoflurane",
  "Sibeprenlimab",
  "Sildenafil",
  "Silodosin",
  "Simeprevir",
  "Simethicone",
  "Simvastatin",
  "Sincalide",
  "Siponimod",
  "Sipuleucel-T",
  "Sirolimus (Conventional)",
  "Sirolimus (Protein Bound)",
  "Sirolimus (Topical)",
  "Sirolimus Products",
  "Sitafloxacin",
  "Skullcap Products",
  "Smallpox and Monkeypox Vaccine (Live)",
  "Sodium Benzoate",
  "Sodium Bicarbonate (Systemic)",
  "Sodium Chloride",
  "Sodium Iodide I131",
  "Sodium Nitrite",
  "Sodium Oxybate",
  "Sodium Perchlorate",
  "Sodium Phosphates",
  "Sodium Picosulfate",
  "Sodium Polystyrene Sulfonate",
  "Sodium Sulfate",
  "Sodium Zirconium Cyclosilicate",
  "Sodium-Glucose Cotransporter 2 (SGLT2) Inhibitors",
  "Sofosbuvir",
  "Sofpironium",
  "Solifenacin",
  "Solriamfetol",
  "Somatostatin Analogs",
  "Somatropin",
  "Sonidegib",
  "Sorbitol",
  "Sotagliflozin",
  "Sotalol",
  "Sotorasib",
  "Soybean",
  "Sparfloxacin",
  "Sparsentan",
  "Sphingosine 1-Phosphate (S1P) Receptor Modulators",
  "Spinach",
  "Spiramycin",
  "Spironolactone",
  "St John's Wort",
  "Stavudine",
  "Stiripentol",
  "Streptokinase",
  "Strontium Ranelate",
  "Succinylcholine",
  "Sucralfate",
  "Sucroferric Oxyhydroxide",
  "Sugammadex",
  "Sulbactam",
  "SulfADIAZINE",
  "SulfaSALAzine",
  "Sulfadoxine",
  "Sulfamethoxazole",
  "Sulfinpyrazone",
  "Sulfonamide Antibiotics",
  "Sulfonamides",
  "Sulfonylureas",
  "Sulodexide",
  "Sulopenem Etzadroxil",
  "Sulpiride",
  "Sulprostone",
  "Sulthiame",
  "Sunvozertinib",
  "Suvorexant",
  "Suzetrigine",
  "Sympathomimetics",
  "Sympathomimetics (Non-Systemic)",
  "Syrian Rue",
  "TOLBUTamide",
  "Tacrolimus (Systemic)",
  "Tacrolimus (Topical)",
  "Tadalafil",
  "Tafamidis",
  "Tafenoquine",
  "Talazoparib",
  "Taletrectinib",
  "Talimogene Laherparepvec",
  "Talniflumate",
  "Talquetamab",
  "Tamoxifen",
  "Tamsulosin",
  "Tapentadol",
  "Tarlatamab",
  "Tasimelteon",
  "Taurolidine",
  "Taurursodiol",
  "Taxane Derivatives",
  "Tazarotene",
  "Tazemetostat",
  "Technetium Tc 99m Medronate",
  "Technetium Tc 99m Oxidronate",
  "Technetium Tc 99m Pyrophosphate",
  "Technetium Tc 99m Sestamibi",
  "Technetium Tc 99m Tetrofosmin",
  "Technetium Tc 99m Tilmanocept",
  "Teclistamab",
  "Tecovirimat",
  "Tedizolid",
  "Teduglutide",
  "Tegoprazan",
  "Teicoplanin",
  "Telavancin",
  "Telisotuzumab Vedotin",
  "Telmisartan",
  "Telotristat Ethyl",
  "Temoporfin",
  "Temozolomide",
  "Temsirolimus",
  "Tenecteplase",
  "Tenofovir Alafenamide",
  "Tenofovir Disoproxil Fumarate",
  "Tenofovir Products",
  "Tenoxicam",
  "Teplizumab",
  "Tepotinib",
  "Terazosin",
  "Terbinafine (Systemic)",
  "Terbutaline",
  "Teriflunomide",
  "Terizidone",
  "Tertomotide",
  "Tesamorelin",
  "Testosterone",
  "Tetrabenazine",
  "Tetracycline (Systemic)",
  "Tetracyclines",
  "Tetrahydrocannabinol",
  "Tetrahydrocannabinol and Cannabidiol",
  "Tetrastarch",
  "Tezacaftor and Ivacaftor",
  "Tezepelumab",
  "Thalidomide",
  "Theodrenaline",
  "Theophylline",
  "Theophylline Derivatives",
  "Therapeutic Antiplatelets",
  "Thiamine",
  "Thiamphenicol",
  "Thiazide and Thiazide-Like Diuretics",
  "Thiazolidinediones",
  "Thiopental",
  "Thiopurine Analogs",
  "Thioridazine",
  "Thiotepa",
  "Thiothixene",
  "Thrombolytic Agents",
  "Thyroid Products",
  "TiZANidine",
  "TiaGABine",
  "Tianeptine",
  "Tiapride",
  "Tibolone",
  "Ticagrelor",
  "Ticlopidine",
  "Tigecycline",
  "Tildrakizumab",
  "Tilidine",
  "Timolol (Ophthalmic)",
  "Timolol (Systemic)",
  "Tinidazole",
  "Tinzaparin",
  "Tiotropium",
  "Tipranavir",
  "Tirzepatide",
  "Tisagenlecleucel",
  "Tisotumab Vedotin",
  "Tivozanib",
  "Tobacco (Smoked)",
  "Tobacco (Smokeless)",
  "Tobramycin (Oral Inhalation)",
  "Tofacitinib",
  "Tolcapone",
  "Tolfenamic Acid",
  "Tolperisone",
  "Tolterodine",
  "Tolvaptan",
  "Topiramate",
  "Topotecan",
  "Toremifene",
  "Torsemide",
  "Tovorafenib",
  "TraMADol",
  "TraZODone",
  "Trabectedin",
  "Tralokinumab",
  "Tranexamic Acid",
  "Tranilast (Systemic)",
  "Tranylcypromine",
  "Trastuzumab",
  "Treosulfan",
  "Treprostinil",
  "Tretinoin (Systemic)",
  "Triamcinolone (Nasal)",
  "Triamcinolone (Ophthalmic)",
  "Triamcinolone (Systemic)",
  "Triamcinolone (Topical)",
  "Triamterene",
  "Triazolam",
  "Triclabendazole",
  "Tricyclic Antidepressants",
  "Trientine",
  "Trifluoperazine",
  "Trifluridine and Tipiracil",
  "Triflusal",
  "Trihexyphenidyl",
  "Trilaciclib",
  "Trimebutine",
  "Trimeprazine",
  "Trimetazidine",
  "Trimethobenzamide",
  "Trimethoprim",
  "Trimipramine",
  "Triprolidine",
  "Triptorelin",
  "Trofinetide",
  "Tropicamide",
  "Tropisetron",
  "Trospium",
  "Tryptophan",
  "Tuberculin Tests",
  "Tucatinib",
  "Turmeric",
  "Typhoid Vaccine",
  "Tyrosine",
  "UGT1A1 Inducers",
  "UGT1A1 Inhibitors",
  "UGT1A1 Substrates",
  "UGT1A6 Inhibitors",
  "UGT1A9 Inducers",
  "UGT2B15 Inhibitors",
  "Ublituximab",
  "Ubrogepant",
  "Udenafil",
  "Ulipristal",
  "Umeclidinium",
  "Unithiol",
  "Upadacitinib",
  "Urapidil",
  "Urea Cycle Disorder Agents",
  "Urinary Acidifying Agents",
  "Urokinase",
  "Ursodiol",
  "Ustekinumab",
  "Vaborbactam",
  "Vaccines",
  "Vaccines (Live)",
  "Vaccines (Non-Live/Inactivated/Non-Replicating)",
  "Vadadustat",
  "Valbenazine",
  "Valerian",
  "Valoctocogene Roxaparvovec",
  "Valproic Acid and Derivatives",
  "Valsartan",
  "Vamorolone",
  "Vancomycin",
  "Vandetanib",
  "Vanzacaftor, Tezacaftor, and Deutivacaftor",
  "Vardenafil",
  "Varenicline (Systemic)",
  "Varicella Virus Vaccine",
  "Varicella Virus-Containing Vaccines",
  "Vasodilators (Organic Nitrates)",
  "Vasopressin",
  "Vecuronium",
  "Vedolizumab",
  "Velpatasvir",
  "Vemurafenib",
  "Venetoclax",
  "Venlafaxine",
  "Verapamil",
  "Vericiguat",
  "Verteporfin",
  "Vesicular Monoamine Transporter 2 (VMAT2) Inhibitors",
  "Vibegron",
  "Vigabatrin",
  "Vilanterol",
  "Vilazodone",
  "Viloxazine",
  "Vimseltinib",
  "VinBLAStine",
  "VinCRIStine",
  "Vindesine",
  "Vinflunine",
  "Vinorelbine",
  "Vismodegib",
  "Vitamin A",
  "Vitamin B12",
  "Vitamin D Analogs",
  "Vitamin E (Systemic)",
  "Vitamin K Antagonists",
  "Vitamins (Fat Soluble)",
  "Voclosporin",
  "Volanesorsen",
  "Vonoprazan",
  "Vorapaxar",
  "Vorasidenib",
  "Voriconazole",
  "Vorinostat",
  "Vortioxetine",
  "Voxilaprevir",
  "Warfarin",
  "White Birch Allergen Extract",
  "Willow Bark",
  "Wormwood",
  "Xanomeline",
  "Xipamide",
  "Yellow Fever Vaccine",
  "Yohimbine",
  "ZOLMitriptan",
  "Zafirlukast",
  "Zaleplon",
  "Zanubrutinib",
  "Zavegepant (Nasal)",
  "Ziconotide",
  "Zidovudine",
  "Ziftomenib",
  "Zileuton",
  "Zinc Salts",
  "Ziprasidone",
  "Zoledronic Acid",
  "Zolpidem",
  "Zongertinib",
  "Zonisamide",
  "Zopiclone",
  "Zoster Vaccine (Live/Attenuated)",
  "Zuclopenthixol",
  "Zuranolone",
];

