/**
 * Hospital formulary drug list for pharmacy interaction checker.
 * Cross-referenced: 陽明院區常備藥品明細表 × MICROMEDEX DrugDex.
 * 469 drugs with known interaction data included.
 */
export const DRUG_LIST: string[] = [
  "ALPRAZolam",
  "ALfentanil",
  "ARIPiprazole",
  "Abacavir",
  "Acarbose",
  "Acemetacin",
  "AcetaZOLAMIDE",
  "Acetaminophen",
  "Acetylcysteine",
  "Acitretin",
  "Acyclovir (Systemic)",
  "Adenosine",
  "Agomelatine",
  "Albuterol",
  "Alcohol (Ethyl)",
  "Alendronate",
  "Alfacalcidol",
  "Alfuzosin",
  "Allopurinol",
  "Alprostadil",
  "Alteplase",
  "Aluminum Hydroxide",
  "AmLODIPine",
  "Amantadine",
  "Amikacin Liposome (Oral Inhalation)",
  "Aminophylline",
  "Amiodarone",
  "Amisulpride (Oral)",
  "Amoxicillin",
  "Ampicillin",
  "Anagrelide",
  "Anastrozole",
  "Apixaban",
  "Ascorbic Acid",
  "Aspirin",
  "Atenolol",
  "Atorvastatin",
  "Atropine (Systemic)",
  "Avibactam",
  "AzaTHIOprine",
  "Azelastine (Nasal)",
  "Azithromycin (Systemic)",
  "BUPivacaine",
  "Bacitracin (Systemic)",
  "Baclofen",
  "Bazedoxifene",
  "Beclomethasone (Systemic)",
  "Bempedoic Acid",
  "Benzbromarone",
  "Benzoyl Peroxide",
  "Benztropine",
  "Betamethasone (Systemic)",
  "Bevacizumab",
  "Bezafibrate",
  "Bicalutamide",
  "Bimatoprost",
  "Biperiden",
  "Bisacodyl",
  "Bismuth Subcitrate",
  "Bisoprolol",
  "Bortezomib",
  "Brexpiprazole",
  "Brimonidine (Topical)",
  "Bromazepam",
  "Bromocriptine",
  "Brompheniramine",
  "Brotizolam",
  "BuPROPion",
  "Budesonide (Systemic)",
  "Buprenorphine",
  "BusPIRone",
  "C / Y and W-135) Conjugate Vaccine / Tetanus Toxoids Vaccines",
  "CARBOplatin",
  "CISplatin",
  "Cabergoline",
  "Calcitriol (Systemic)",
  "Calcium Salts",
  "Canagliflozin",
  "Carbachol",
  "Carbidopa",
  "Carisoprodol",
  "Carvedilol",
  "CeFAZolin",
  "CefTAZidime",
  "CefTRIAXone",
  "Cefmetazole",
  "Cefoperazone",
  "Cefpirome",
  "Ceftizoxime",
  "Cefuroxime",
  "Celecoxib",
  "Cephalexin",
  "Cephradine",
  "Cetirizine (Systemic)",
  "Chloral Hydrate/Chloral Betaine",
  "Chlorpheniramine",
  "Cholestyramine Resin",
  "Ciclesonide (Oral Inhalation)",
  "Cilostazol",
  "Ciprofloxacin (Systemic)",
  "Citalopram",
  "Citric Acid Derivatives",
  "Clarithromycin",
  "Clindamycin (Systemic)",
  "CloNIDine",
  "CloZAPine",
  "ClomiPHENE",
  "ClonazePAM",
  "Clopidogrel",
  "Codeine",
  "Colchicine",
  "Colistimethate",
  "Crisaborole",
  "CycloPHOSphamide",
  "Cyclobenzaprine",
  "Cyproheptadine",
  "Cyproterone",
  "DOBUTamine",
  "DOCEtaxel",
  "DOPamine",
  "DULoxetine",
  "Dabigatran Etexilate",
  "Dapagliflozin",
  "Dapoxetine",
  "Darbepoetin Alfa",
  "Deferoxamine",
  "Denosumab",
  "Desloratadine",
  "Desmopressin",
  "DexAMETHasone (Systemic)",
  "Dexlansoprazole",
  "DexmedeTOMIDine",
  "Dextran",
  "Dextromethorphan",
  "DiazePAM",
  "Diclofenac (Systemic)",
  "Dicloxacillin",
  "Digoxin",
  "Dihydroergotamine",
  "DilTIAZem",
  "Dimethicone (Systemic)",
  "DiphenhydrAMINE (Systemic)",
  "Dipyridamole",
  "Domperidone",
  "Donepezil",
  "Doxazosin",
  "Doxepin (Systemic)",
  "Doxycycline",
  "Drospirenone-Containing Products",
  "Dupilumab",
  "Dutasteride",
  "EPHEDrine (Systemic)",
  "EPINEPHrine (Systemic)",
  "Edetate CALCIUM Disodium",
  "Edoxaban",
  "Efavirenz",
  "Emedastine (Systemic)",
  "Empagliflozin",
  "Entacapone",
  "Eplerenone",
  "Ergonovine",
  "Ertapenem",
  "Escitalopram",
  "Esomeprazole",
  "Estazolam",
  "Estrogen Derivatives",
  "Ethambutol",
  "Ethinyl Estradiol-Containing Products",
  "Etofenamate",
  "Etoricoxib",
  "Ezetimibe",
  "Famciclovir",
  "Famotidine",
  "Febuxostat",
  "Felodipine",
  "Fenofibrate and Derivatives",
  "Fenoterol",
  "FentaNYL",
  "Fexofenadine",
  "Filgrastim",
  "Finasteride",
  "Fluconazole",
  "Fludeoxyglucose F 18",
  "Flunitrazepam",
  "Fluoroestradiol F18",
  "Fluorouracil (Systemic)",
  "Flupentixol",
  "Flurazepam",
  "Flurbiprofen (Systemic)",
  "Fluticasone (Topical)",
  "Fluvastatin",
  "FluvoxaMINE",
  "Folic Acid",
  "Formoterol",
  "Fosinopril",
  "Furosemide",
  "Fusidic Acid (Systemic)",
  "Gabapentin (Immediate Release)",
  "Gemcitabine (Systemic)",
  "Gemifloxacin",
  "Gentamicin (Systemic)",
  "Glimepiride",
  "Glucosamine",
  "GlyBURIDE",
  "Glycopyrrolate (Systemic)",
  "Glycopyrronium (Topical)",
  "Haloperidol",
  "Heparin",
  "HydrALAZINE",
  "HydrOXYzine",
  "HydroCHLOROthiazide",
  "Hydrocortisone (Systemic)",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "ISOtretinoin (Systemic)",
  "Ibuprofen (Systemic)",
  "Imidapril",
  "Imipenem",
  "Imipramine",
  "Indacaterol",
  "Indomethacin (Systemic)",
  "Insulin",
  "Ipratropium (Nasal)",
  "Irbesartan",
  "Irinotecan Products",
  "Isoconazole",
  "Isoniazid",
  "Itraconazole",
  "Ivabradine",
  "Ketoconazole (Systemic)",
  "Ketoprofen",
  "Ketorolac (Systemic)",
  "Ketotifen (Systemic)",
  "LORazepam",
  "Labetalol",
  "Lacidipine",
  "Lacosamide",
  "LamiVUDine",
  "LamoTRIgine",
  "Lansoprazole",
  "Latanoprost",
  "Lercanidipine",
  "Letrozole",
  "LevETIRAcetam",
  "LevoFLOXacin (Systemic)",
  "Levocetirizine",
  "Levodopa (Oral)",
  "Levonorgestrel (Systemic)",
  "Levothyroxine",
  "Lidocaine (Systemic)",
  "LinaGLIPtin",
  "Linezolid",
  "Liraglutide",
  "Lithium",
  "Lixisenatide",
  "Loperamide",
  "Loratadine",
  "Losartan",
  "Lovastatin",
  "Lurasidone",
  "Lysozyme",
  "Magnesium Salts",
  "Mannitol (Systemic)",
  "Mebendazole",
  "MedroxyPROGESTERone",
  "Mefenamic Acid",
  "Megestrol",
  "Melatonin",
  "Melitracen",
  "Meloxicam",
  "Memantine",
  "Meperidine",
  "Meropenem",
  "Mesalamine",
  "MetFORMIN",
  "MethIMAzole",
  "Methadone",
  "Methotrexate",
  "MethylPREDNISolone (Systemic)",
  "Methylergonovine",
  "Methylphenidate",
  "Metoclopramide",
  "Metoprolol",
  "MetroNIDAZOLE (Systemic)",
  "Mexiletine",
  "MiFEPRIStone",
  "MiSOPROStol",
  "Midazolam",
  "Midodrine",
  "Milk Thistle",
  "Milnacipran",
  "Mineral Oil",
  "Minocycline (Systemic)",
  "Mirabegron",
  "Mirtazapine",
  "Mizolastine",
  "Mometasone (Topical)",
  "Morphine (Systemic)",
  "Moxifloxacin (Systemic)",
  "NIFEdipine (Systemic)",
  "Naloxone",
  "Nebivolol",
  "Neomycin (Systemic)",
  "NiCARdipine",
  "Nicergoline",
  "Nicorandil",
  "Nicotine",
  "Nintedanib",
  "Nisoldipine",
  "Nitroglycerin",
  "Norepinephrine",
  "OLANZapine",
  "OXcarbazepine",
  "Octreotide",
  "Ofloxacin (Systemic)",
  "Olmesartan",
  "Olodaterol",
  "Omeprazole",
  "Oseltamivir",
  "Oxaliplatin",
  "OxyBUTYnin",
  "OxyCODONE",
  "Oxymetazoline (Topical)",
  "Oxytocin",
  "PACLitaxel (Conventional)",
  "PEMEtrexed",
  "PHENobarbital",
  "Palopegteriparatide",
  "Pancrelipase",
  "Pantoprazole",
  "Parecoxib",
  "Penicillin G",
  "Pentoxifylline",
  "Perampanel",
  "Phenylephrine (Systemic)",
  "Phenytoin",
  "Phytonadione",
  "Pilocarpine (Systemic)",
  "Pimecrolimus",
  "Pimozide",
  "Pioglitazone",
  "Pipemidic Acid",
  "Piperacillin",
  "Piracetam",
  "Pirfenidone",
  "Pitavastatin",
  "Pneumococcal Vaccines",
  "Polyethylene Glycol-Electrolyte Solution",
  "Polymyxin B",
  "Potassium Citrate",
  "Potassium Salts",
  "Pramipexole",
  "Prasugrel",
  "Pravastatin",
  "PrednisoLONE (Systemic)",
  "Pregabalin",
  "Prilocaine",
  "Prochlorperazine",
  "Products Containing Ethanol",
  "Progesterone",
  "Propacetamol",
  "Propafenone",
  "Propofol",
  "Propranolol",
  "Propylthiouracil",
  "Pseudoephedrine",
  "Pyrazinamide",
  "Pyridoxine",
  "QUEtiapine",
  "Quinapril",
  "RABEprazole",
  "RaNITIdine",
  "Racecadotril",
  "Raloxifene",
  "Ramelteon",
  "Ramipril",
  "Rasagiline",
  "Repaglinide",
  "Ribavirin (Systemic)",
  "RisperiDONE",
  "Ritodrine",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Rosuvastatin",
  "SAXagliptin",
  "SITagliptin",
  "Salicylic Acid",
  "Salmeterol",
  "Scopolamine",
  "Semaglutide",
  "Senna",
  "Sertraline",
  "Sevoflurane",
  "Sildenafil",
  "Simethicone",
  "Simvastatin",
  "Sodium Bicarbonate (Systemic)",
  "Sodium Picosulfate",
  "Sofosbuvir",
  "Solifenacin",
  "Sorbitol",
  "Spironolactone",
  "Strontium Ranelate",
  "Succinylcholine",
  "Sulbactam",
  "SulfaSALAzine",
  "Sulfamethoxazole",
  "Sulfinpyrazone",
  "Sulpiride",
  "Tacrolimus (Topical)",
  "Tadalafil",
  "Tamoxifen",
  "Tamsulosin",
  "Tazarotene",
  "Teicoplanin",
  "Telmisartan",
  "Tenofovir Disoproxil Fumarate",
  "Tenoxicam",
  "Terazosin",
  "Terbinafine (Systemic)",
  "Terbutaline",
  "Testosterone",
  "Tetracycline (Systemic)",
  "Thalidomide",
  "Theophylline",
  "Thiamine",
  "TiaGABine",
  "Ticlopidine",
  "Tigecycline",
  "Timolol (Systemic)",
  "Tiotropium",
  "Tirzepatide",
  "Tobramycin (Oral Inhalation)",
  "Tolperisone",
  "Tolterodine",
  "Topiramate",
  "Torsemide",
  "TraMADol",
  "TraZODone",
  "Tranexamic Acid",
  "Trastuzumab",
  "Triamcinolone (Nasal)",
  "Triamcinolone (Systemic)",
  "Triazolam",
  "Trihexyphenidyl",
  "Trimethoprim",
  "Triprolidine",
  "Tropicamide",
  "Ulipristal",
  "Umeclidinium",
  "Urokinase",
  "Valsartan",
  "Vancomycin",
  "Velpatasvir",
  "Venlafaxine",
  "Verapamil",
  "Vilanterol",
  "VinCRIStine",
  "Vinorelbine",
  "Vitamin D Analogs",
  "Vortioxetine",
  "Warfarin",
  "Zaleplon",
  "Zidovudine",
  "Ziprasidone",
  "Zoledronic Acid",
  "Zolpidem",
  "Zopiclone",
];
