#!/usr/bin/env python3
"""PR-0 FHIR standardization baseline audit.

Read-only. Connects to Supabase via SYNC_ENV_PATH or backend/.env.his-sync.
Answers 6 questions and writes docs/fhir-baseline-report.md.

Usage:
    export SYNC_ENV_PATH=/absolute/path/to/backend/.env.his-sync
    python3 backend/scripts/fhir_baseline_audit.py
"""
from __future__ import annotations

import asyncio
import csv
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_ROOT.parent
sys.path.insert(0, str(BACKEND_ROOT))

FHIR_KIT = REPO_ROOT / "FHIR功能"
LEGACY_ATC_CSV = FHIR_KIT / "藥物標準化" / "atc_drugs.csv"
LOINC_CSV = FHIR_KIT / "lab轉FHIR" / "loinc_labs.csv"
# Primary source: generated by backend/scripts/build_formulary_csv.py from
# the Yangming hospital formulary xlsx + antibiotic list xlsx.
FORMULARY_CSV = BACKEND_ROOT / "app" / "fhir" / "code_maps" / "drug_formulary.csv"
DDI_ALIAS_JSON = BACKEND_ROOT / "app" / "fhir" / "his_ddi_alias_map.json"
DDI_EXCLUSION_JSON = BACKEND_ROOT / "app" / "fhir" / "his_ddi_exclusion_list.json"

OUTPUT_MD = REPO_ROOT / "docs" / "fhir-baseline-report.md"


def get_database_url() -> str:
    env_path = os.environ.get("SYNC_ENV_PATH")
    env_file = Path(env_path) if env_path else BACKEND_ROOT / ".env.his-sync"
    if not env_file.exists():
        raise RuntimeError(f"Env file not found: {env_file}")
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line.startswith("DATABASE_URL="):
            url = line.split("=", 1)[1].strip().strip('"').strip("'")
            if url.startswith("postgresql://"):
                url = url.replace("postgresql://", "postgresql+asyncpg://", 1)
            return url
    raise RuntimeError("DATABASE_URL not in env file")


def load_atc_csv() -> dict[str, dict]:
    """Load the unified formulary CSV (Yangming formulary + ABX + legacy merged).

    Schema: odr_code, atc_code, ingredient, brand_name, unit,
            is_antibiotic, kidney_relevant, rxnorm_cui, source, notes
    """
    out = {}
    if not FORMULARY_CSV.exists():
        raise RuntimeError(
            f"{FORMULARY_CSV} not found. "
            "Run `python3 backend/scripts/build_formulary_csv.py` first."
        )
    with FORMULARY_CSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            code = row["odr_code"].strip()
            if code and row.get("atc_code"):
                out[code] = row
    return out


def load_legacy_atc_csv() -> dict[str, dict]:
    """Load the legacy (pre-formulary) CSV for comparison only."""
    out = {}
    if not LEGACY_ATC_CSV.exists():
        return out
    with LEGACY_ATC_CSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            out[row["odr_code"].strip()] = row
    return out


def load_loinc_csv() -> dict[str, dict]:
    out = {}
    with LOINC_CSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            out[row["lab_code"].strip()] = row
    return out


def load_ddi_alias() -> dict[str, list[str]]:
    raw = json.loads(DDI_ALIAS_JSON.read_text(encoding="utf-8"))
    return {k: v for k, v in raw.items() if not k.startswith("_") and isinstance(v, list)}


def load_ddi_exclusion() -> set[str]:
    raw = json.loads(DDI_EXCLUSION_JSON.read_text(encoding="utf-8"))
    return {e["odr_code"] for e in raw.get("exclusions", []) if "odr_code" in e}


def load_his_lab_codes() -> set[str]:
    import importlib.util
    mod_path = BACKEND_ROOT / "app" / "fhir" / "his_lab_mapping.py"
    spec = importlib.util.spec_from_file_location("his_lab_mapping", mod_path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return set(mod.HIS_LAB_MAP.keys())


async def audit() -> dict[str, Any]:
    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    atc_map = load_atc_csv()
    legacy_atc_map = load_legacy_atc_csv()
    loinc_map = load_loinc_csv()
    ddi_alias = load_ddi_alias()
    ddi_exclusion = load_ddi_exclusion()
    his_lab_codes = load_his_lab_codes()

    url = get_database_url()
    engine = create_async_engine(
        url,
        connect_args={
            "prepared_statement_cache_size": 0,
            "statement_cache_size": 0,
            "command_timeout": 120,
        },
    )

    results: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "formulary_total": len(atc_map),
        "legacy_atc_csv_total": len(legacy_atc_map),
        "loinc_csv_total": len(loinc_map),
        "ddi_alias_total": len(ddi_alias),
        "ddi_exclusion_total": len(ddi_exclusion),
        "his_lab_map_total": len(his_lab_codes),
    }

    async with engine.connect() as conn:
        r = await conn.execute(text("SELECT COUNT(*) FROM medications"))
        results["medications_total_rows"] = r.scalar()

        r = await conn.execute(text("SELECT COUNT(DISTINCT patient_id) FROM medications"))
        results["medications_distinct_patients"] = r.scalar()

        # Q1: ODR_CODE → ATC hit rate
        r = await conn.execute(text(
            "SELECT order_code, COUNT(*) AS cnt FROM medications "
            "WHERE order_code IS NOT NULL AND order_code <> '' "
            "GROUP BY order_code"
        ))
        odr_rows = [(row[0], row[1]) for row in r]
        distinct_odr = {c for c, _ in odr_rows}
        total_with_odr = sum(cnt for _, cnt in odr_rows)
        odr_hit_atc = {c for c in distinct_odr if c in atc_map}
        weighted_hit_atc = sum(cnt for c, cnt in odr_rows if c in atc_map)

        results["q1_distinct_odr_codes"] = len(distinct_odr)
        results["q1_rows_with_odr"] = total_with_odr
        results["q1_distinct_hit"] = len(odr_hit_atc)
        results["q1_distinct_hit_pct"] = round(100 * len(odr_hit_atc) / len(distinct_odr), 1) if distinct_odr else 0
        results["q1_row_weighted_hit"] = weighted_hit_atc
        results["q1_row_weighted_pct"] = round(100 * weighted_hit_atc / total_with_odr, 1) if total_with_odr else 0

        # Q2: Top-30 unmapped ODR_CODEs by frequency
        r = await conn.execute(text(
            "SELECT order_code, COUNT(*) AS cnt, "
            "       MAX(name) AS sample_name, "
            "       COUNT(DISTINCT patient_id) AS n_patients "
            "FROM medications "
            "WHERE order_code IS NOT NULL AND order_code <> '' "
            "GROUP BY order_code "
            "ORDER BY cnt DESC"
        ))
        all_codes = [
            {"code": row[0], "cnt": row[1], "sample_name": row[2], "n_patients": row[3]}
            for row in r
        ]
        unmapped_top = [c for c in all_codes if c["code"] not in atc_map][:30]
        results["q2_top_unmapped"] = unmapped_top

        # How many of Q2 top-30 are known non-drugs (exclusion list)?
        unmapped_top_in_exclusion = [c for c in unmapped_top if c["code"] in ddi_exclusion]
        results["q2_top_unmapped_in_exclusion"] = len(unmapped_top_in_exclusion)

        # How many of unmapped top-30 have a DDI alias already?
        unmapped_top_in_alias = [c for c in unmapped_top if c["code"] in ddi_alias]
        results["q2_top_unmapped_in_ddi_alias"] = len(unmapped_top_in_alias)

        # Q3: HIS LAB_CODE → LOINC coverage (file-to-file)
        loinc_covered = his_lab_codes & set(loinc_map.keys())
        results["q3_his_lab_codes_total"] = len(his_lab_codes)
        results["q3_loinc_csv_total"] = len(loinc_map)
        results["q3_overlap"] = len(loinc_covered)
        results["q3_overlap_pct"] = round(100 * len(loinc_covered) / len(his_lab_codes), 1) if his_lab_codes else 0

        # Q4/Q5: DDI baseline + ATC ceiling
        r = await conn.execute(text(
            "SELECT patient_id, generic_name, name, order_code "
            "FROM medications "
            "WHERE status = 'active'"
        ))
        by_patient: dict[str, list[dict]] = defaultdict(list)
        for pid, generic, name, code in r:
            by_patient[pid].append({
                "generic": generic,
                "name": name,
                "code": code,
            })

        r = await conn.execute(text("SELECT drug1, drug2 FROM drug_interactions"))
        ddi_pairs_lower: set[frozenset] = set()
        ddi_pairs_exact: set[frozenset] = set()
        ddi_name_set_lower: set[str] = set()
        ddi_name_set_exact: set[str] = set()
        for d1, d2 in r:
            if not d1 or not d2:
                continue
            d1 = d1.strip()
            d2 = d2.strip()
            if not d1 or not d2 or d1 == d2:
                continue
            ddi_pairs_exact.add(frozenset({d1, d2}))
            ddi_pairs_lower.add(frozenset({d1.lower(), d2.lower()}))
            ddi_name_set_exact.add(d1)
            ddi_name_set_exact.add(d2)
            ddi_name_set_lower.add(d1.lower())
            ddi_name_set_lower.add(d2.lower())
        results["q4_ddi_table_pairs"] = len(ddi_pairs_lower)
        results["q4_ddi_table_drugs"] = len(ddi_name_set_lower)

        total_pairs = 0
        total_current_hits_exact = 0  # replicates production case-sensitive query
        total_current_hits_lower = 0  # case-insensitive sanity check
        total_hits_with_alias = 0  # simulate: apply DDI alias map at query time
        total_atc_both_covered = 0
        drugs_matching_ddi_exact: set[str] = set()
        drugs_matching_ddi_lower: set[str] = set()
        # ODR_CODE coverage among active meds
        active_odr_in_alias = 0
        active_odr_not_in_alias = 0
        active_odr_missing = 0
        active_odr_in_atc = 0
        patient_stats = []
        for pid, meds in by_patient.items():
            active_tokens_exact: list[tuple[str, str | None]] = []  # original case
            active_tokens_lower: list[tuple[str, str | None]] = []  # lowercased
            active_tokens_alias: list[tuple[str, str | None]] = []  # if DDI alias map applied
            for m in meds:
                # Track ODR_CODE coverage
                code = m["code"]
                if not code:
                    active_odr_missing += 1
                elif code in ddi_alias:
                    active_odr_in_alias += 1
                else:
                    active_odr_not_in_alias += 1
                if code and code in atc_map:
                    active_odr_in_atc += 1

                # Build lookup tokens
                raw = (m["generic"] or m["name"] or "").strip()
                for part in raw.split(" / "):
                    p_ex = part.strip()
                    if p_ex:
                        active_tokens_exact.append((p_ex, code))
                        active_tokens_lower.append((p_ex.lower(), code))
                        if p_ex in ddi_name_set_exact:
                            drugs_matching_ddi_exact.add(p_ex)
                        if p_ex.lower() in ddi_name_set_lower:
                            drugs_matching_ddi_lower.add(p_ex.lower())

                # "As if alias map applied": use alias_map[code] when code is in map,
                # else fallback to lowered generic/name
                if code and code in ddi_alias:
                    for aliased in ddi_alias[code]:
                        if aliased:
                            active_tokens_alias.append((aliased.lower(), code))
                else:
                    for part in raw.split(" / "):
                        p_lo = part.strip().lower()
                        if p_lo:
                            active_tokens_alias.append((p_lo, code))

            seen: set[frozenset] = set()
            pair_count = 0
            hits_exact = 0
            hits_lower = 0
            atc_both = 0
            for i in range(len(active_tokens_lower)):
                for j in range(i + 1, len(active_tokens_lower)):
                    a_lo, ca = active_tokens_lower[i]
                    b_lo, cb = active_tokens_lower[j]
                    a_ex = active_tokens_exact[i][0]
                    b_ex = active_tokens_exact[j][0]
                    if a_lo == b_lo:
                        continue
                    key = frozenset({a_lo, b_lo})
                    if key in seen:
                        continue
                    seen.add(key)
                    pair_count += 1
                    if frozenset({a_ex, b_ex}) in ddi_pairs_exact:
                        hits_exact += 1
                    if key in ddi_pairs_lower:
                        hits_lower += 1
                    if ca in atc_map and cb in atc_map:
                        atc_both += 1

            # Separately count hits using alias-normalised tokens
            seen_alias: set[frozenset] = set()
            hits_alias = 0
            for i in range(len(active_tokens_alias)):
                for j in range(i + 1, len(active_tokens_alias)):
                    a_lo = active_tokens_alias[i][0]
                    b_lo = active_tokens_alias[j][0]
                    if a_lo == b_lo:
                        continue
                    key = frozenset({a_lo, b_lo})
                    if key in seen_alias:
                        continue
                    seen_alias.add(key)
                    if key in ddi_pairs_lower:
                        hits_alias += 1

            total_pairs += pair_count
            total_current_hits_exact += hits_exact
            total_current_hits_lower += hits_lower
            total_hits_with_alias += hits_alias
            total_atc_both_covered += atc_both
            patient_stats.append({
                "patient_id": pid,
                "n_active_drug_tokens": len(active_tokens_lower),
                "n_unique_pairs": pair_count,
                "current_ddi_hits_exact": hits_exact,
                "current_ddi_hits_lower": hits_lower,
                "hits_with_alias_applied": hits_alias,
                "atc_ceiling_pairs": atc_both,
            })

        patient_stats.sort(key=lambda x: -x["n_unique_pairs"])
        results["q4_total_patients_with_active"] = len(by_patient)
        results["q4_total_unique_active_pairs"] = total_pairs
        results["q4_total_current_ddi_hits_exact"] = total_current_hits_exact
        results["q4_total_current_ddi_hits_lower"] = total_current_hits_lower
        results["q4_total_hits_with_alias_applied"] = total_hits_with_alias
        results["q4_active_odr_in_alias"] = active_odr_in_alias
        results["q4_active_odr_not_in_alias"] = active_odr_not_in_alias
        results["q4_active_odr_missing"] = active_odr_missing
        results["q4_active_odr_in_atc"] = active_odr_in_atc
        results["q4_active_med_total"] = active_odr_in_alias + active_odr_not_in_alias + active_odr_missing
        results["q4_mean_pairs_per_patient"] = round(total_pairs / len(by_patient), 1) if by_patient else 0
        results["q4_drugs_matching_ddi_exact"] = sorted(drugs_matching_ddi_exact)[:20]
        results["q4_drugs_matching_ddi_lower"] = sorted(drugs_matching_ddi_lower)[:20]
        results["q4_drugs_matching_ddi_exact_count"] = len(drugs_matching_ddi_exact)
        results["q4_drugs_matching_ddi_lower_count"] = len(drugs_matching_ddi_lower)
        results["q5_total_pairs_both_atc_covered"] = total_atc_both_covered
        results["q5_atc_ceiling_pct"] = round(100 * total_atc_both_covered / total_pairs, 1) if total_pairs else 0
        results["q5_current_match_pct_exact"] = round(100 * total_current_hits_exact / total_pairs, 1) if total_pairs else 0
        results["q5_current_match_pct_lower"] = round(100 * total_current_hits_lower / total_pairs, 1) if total_pairs else 0
        results["q5_alias_applied_pct"] = round(100 * total_hits_with_alias / total_pairs, 1) if total_pairs else 0
        results["patient_stats"] = patient_stats

        # Q6: ODR_CODE overlap between his_ddi_alias_map and atc_drugs.csv
        alias_codes = set(ddi_alias.keys())
        atc_codes = set(atc_map.keys())
        overlap = alias_codes & atc_codes
        results["q6_ddi_alias_codes"] = len(alias_codes)
        results["q6_atc_csv_codes"] = len(atc_codes)
        results["q6_overlap"] = len(overlap)
        results["q6_only_alias_not_atc"] = sorted(alias_codes - atc_codes)[:20]
        results["q6_only_atc_not_alias"] = sorted(atc_codes - alias_codes)[:20]

        # Supplemental: how many ODR_CODEs in DB are covered by alias map?
        db_covered_by_alias = {c for c in distinct_odr if c in alias_codes}
        results["q6_db_odr_covered_by_alias"] = len(db_covered_by_alias)
        results["q6_db_odr_covered_by_alias_pct"] = round(100 * len(db_covered_by_alias) / len(distinct_odr), 1) if distinct_odr else 0

    await engine.dispose()
    return results


def render_markdown(r: dict[str, Any]) -> str:
    lines: list[str] = []
    w = lines.append
    w("# FHIR Standardization Baseline Report (PR-0)")
    w("")
    w(f"生成時間：{r['generated_at']}")
    w("")
    w("來源：Supabase production (ap-southeast-2) via `backend/.env.his-sync`")
    w("")
    w("---")
    w("")
    w("## 對照表檔案規模")
    w("")
    w("| 檔案 | 筆數 | 角色 |")
    w("|------|-----:|------|")
    w(f"| **`backend/app/fhir/code_maps/drug_formulary.csv`** | **{r['formulary_total']}** | **PRIMARY（院區形成品 + ABX + 手動補碼）** |")
    w(f"| `FHIR功能/藥物標準化/atc_drugs.csv`（舊 baseline 用） | {r['legacy_atc_csv_total']} | 多半已被 formulary 包含，保留做 `kidney_relevant` 參考 |")
    w(f"| `FHIR功能/lab轉FHIR/loinc_labs.csv` | {r['loinc_csv_total']} | 交集 < 30%，不採用 |")
    w(f"| `backend/app/fhir/his_ddi_alias_map.json` | {r['ddi_alias_total']} | DDI 名稱對齊（暫留） |")
    w(f"| `backend/app/fhir/his_ddi_exclusion_list.json` | {r['ddi_exclusion_total']} | 非藥物排除（維持） |")
    w(f"| `backend/app/fhir/his_lab_mapping.HIS_LAB_MAP` | {r['his_lab_map_total']} | 本院 LAB_CODE → ChatICU key |")
    w("")
    w("## DB 規模")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| `medications` 總筆數 | {r['medications_total_rows']} |")
    w(f"| 有 medications 的病人數 | {r['medications_distinct_patients']} |")
    w(f"| `drug_interactions` 中的唯一藥對數 | {r['q4_ddi_table_pairs']} |")
    w("")
    w("---")
    w("")
    w("## Q1：藥物標準碼命中率（ODR_CODE → drug_formulary.csv）")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| 有 `order_code` 的 medications 列數 | {r['q1_rows_with_odr']} |")
    w(f"| distinct ODR_CODE 數 | {r['q1_distinct_odr_codes']} |")
    w(f"| distinct 命中 drug_formulary.csv（含 ATC） | {r['q1_distinct_hit']} ({r['q1_distinct_hit_pct']}%) |")
    w(f"| 以列為權重計算的命中 | {r['q1_row_weighted_hit']} ({r['q1_row_weighted_pct']}%) |")
    w("")
    w("**判讀**：")
    w("")
    if r['q1_row_weighted_pct'] >= 70:
        w("- 列權重命中率 ≥ 70%，**可直接進 PR-3**。")
    elif r['q1_row_weighted_pct'] >= 40:
        w("- 列權重命中率 40-70%，建議**先擴 atc_drugs.csv**（針對 Q2 top-30）再進 PR-3。")
    else:
        w("- 列權重命中率 < 40%，**atc_drugs.csv 與本院 ODR_CODE 慣例差距大**，PR-3 效益有限。")
        w("  建議：(a) 花時間擴表，或 (b) 優先做 PR-2 RxNorm 自動補碼以彌補。")
    w("")
    w("## Q2：Top-30 未命中 ODR_CODE（依出現頻率）")
    w("")
    w("| # | ODR_CODE | 樣本名稱 | 筆數 | 病人數 | 在 exclusion? | 在 DDI alias? |")
    w("|--:|----------|---------|-----:|------:|:------------:|:------------:|")
    for i, u in enumerate(r['q2_top_unmapped'], 1):
        code = u['code']
        ex = "✓" if r.get("_ddi_exclusion_set") and code in r["_ddi_exclusion_set"] else ""
        al = "✓" if r.get("_ddi_alias_set") and code in r["_ddi_alias_set"] else ""
        w(f"| {i} | `{code}` | {u['sample_name'][:40] if u['sample_name'] else ''} | {u['cnt']} | {u['n_patients']} | {ex} | {al} |")
    w("")
    w(f"- Top-30 中屬於 DDI exclusion（非藥物）：{r['q2_top_unmapped_in_exclusion']} 筆")
    w(f"- Top-30 中已在 DDI alias 內（有藥名但無 ATC）：{r['q2_top_unmapped_in_ddi_alias']} 筆")
    w("")
    w("**擴表 backlog**：上表扣除 exclusion 後的項目，請在 `backend/app/fhir/code_maps/drug_formulary_gaps.csv` 的 `suggested_atc` 欄位填入 ATC，然後重跑 `build_formulary_csv.py` 合併。")
    w("")
    w("## Q3：Lab 標準碼命中率（HIS_LAB_MAP ∩ loinc_labs.csv）")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| HIS_LAB_MAP 總 LAB_CODE 數 | {r['q3_his_lab_codes_total']} |")
    w(f"| loinc_labs.csv 總 LAB_CODE 數 | {r['q3_loinc_csv_total']} |")
    w(f"| 交集（可直接對到 LOINC） | {r['q3_overlap']} ({r['q3_overlap_pct']}%) |")
    w("")
    w("**判讀**：")
    w("")
    if r['q3_overlap_pct'] >= 60:
        w("- 交集 ≥ 60%，PR-3 Lab 段可行；剩餘由 `his_lab_mapping.py` 的 ChatICU key 再查 `loinc_map.py` 做第二層對應。")
    elif r['q3_overlap_pct'] >= 30:
        w("- 交集 30-60%，建議**先跑現有 ChatICU key → LOINC 管道**（已有），不急於用 `loinc_labs.csv`。")
    else:
        w("- 交集 < 30%，`loinc_labs.csv` 對本院 LAB_CODE 意義不大。直接用 `loinc_map.py` 現成的 ChatICU key 對應即可。")
    w("")
    w("## Q4：現行 DDI 命中基準")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| 有 active 藥的病人數 | {r['q4_total_patients_with_active']} |")
    w(f"| active 藥對（unique pair，已拆組合藥）總數 | {r['q4_total_unique_active_pairs']} |")
    w(f"| DDI 表中 unique 藥對數 | {r['q4_ddi_table_pairs']} |")
    w(f"| DDI 表中 unique 藥名數 | {r['q4_ddi_table_drugs']} |")
    w(f"| **production 現行命中（case-sensitive 精確比對）** | **{r['q4_total_current_ddi_hits_exact']} ({r['q5_current_match_pct_exact']}%)** |")
    w(f"| 若改 case-insensitive 比對可命中 | {r['q4_total_current_ddi_hits_lower']} ({r['q5_current_match_pct_lower']}%) |")
    w(f"| **若在 query time 套用 `his_ddi_alias_map.json` 後可命中** | **{r['q4_total_hits_with_alias_applied']} ({r['q5_alias_applied_pct']}%)** |")
    w(f"| 每位病人平均藥對數 | {r['q4_mean_pairs_per_patient']} |")
    w("")
    w("### Active 藥的 ODR_CODE 分布")
    w("")
    w("| 指標 | 筆數 | 佔 active 藥 |")
    w("|------|----:|-----------:|")
    tot = r['q4_active_med_total']
    pct = lambda n: f"{round(100*n/tot, 1)}%" if tot else "n/a"
    w(f"| active 藥總列數 | {tot} | 100% |")
    w(f"| ODR_CODE 在 `his_ddi_alias_map.json` 中 | {r['q4_active_odr_in_alias']} | {pct(r['q4_active_odr_in_alias'])} |")
    w(f"| ODR_CODE 不在 alias map 中 | {r['q4_active_odr_not_in_alias']} | {pct(r['q4_active_odr_not_in_alias'])} |")
    w(f"| 無 ODR_CODE | {r['q4_active_odr_missing']} | {pct(r['q4_active_odr_missing'])} |")
    w(f"| ODR_CODE 在 `atc_drugs.csv` 中 | {r['q4_active_odr_in_atc']} | {pct(r['q4_active_odr_in_atc'])} |")
    w("")
    if r['q4_total_current_ddi_hits_exact'] == 0:
        w("> **重大發現：production 現行 DDI 比對全滅（0 命中）**。")
        w(">")
        w("> 進一步驗證 3 種策略都是 0：")
        w("> - case-sensitive exact（production 現況）：0")
        w("> - case-insensitive（簡單 fix）：0")
        w("> - 套用 `his_ddi_alias_map.json`（理論上把 ODR_CODE → clean generic）：0")
        w(">")
        w(f"> 我已驗證 alias map 的 50 個乾淨 generic 中，**51 個確實存在於 `drug_interactions.drug1/drug2`**（覆蓋 OK）。但實際 active 藥對的**組合**（e.g. {{Fentanyl, Neuromuscular-Blocking Agents}}）在 DDI 表**沒有 entry**。")
        w(">")
        w("> **真正的根因**：`drug_interactions` 表的 8,756 條藥對是通用藥典，但本院 ICU 實際用藥組合（鎮痛鎮靜 + 抗生素 + 支持療法）和表中藥對的交集極小。")
        w(">")
        w("> 因此 FHIR ATC 標準化只是**必要不充分條件**。光加 ATC 欄位不能修好 DDI，還要：")
        w("> - (a) 用 ATC class 去圖查 `drug_graph_bridge.py` 的 class node（現有機制，未串到 DDI）")
        w("> - (b) 或擴 `drug_interactions` 加 ATC 欄 + class-level 藥對規則")
        w("> - (c) 或改用外部 DDI 服務（Lexicomp/DrugBank API）")
        w("")
    w("### Active 藥組分中，可直接對到 DDI 表的藥名")
    w("")
    w(f"- case-sensitive 能直接對到：**{r['q4_drugs_matching_ddi_exact_count']}** 種")
    w(f"  - 前 20：{', '.join(f'`{d}`' for d in r['q4_drugs_matching_ddi_exact'])}")
    w(f"- case-insensitive 能對到：**{r['q4_drugs_matching_ddi_lower_count']}** 種")
    w(f"  - 前 20：{', '.join(f'`{d}`' for d in r['q4_drugs_matching_ddi_lower'])}")
    w("")
    w("### 各病人明細（藥對數前 10）")
    w("")
    w("| patient_id | active 藥組分 | 藥對數 | 現行 exact | lower | **alias 套用** | ATC 雙邊覆蓋 |")
    w("|-----------|--------------:|-----:|----------:|-----:|------------:|-----------:|")
    for p in r['patient_stats'][:10]:
        w(f"| `{p['patient_id']}` | {p['n_active_drug_tokens']} | {p['n_unique_pairs']} | {p['current_ddi_hits_exact']} | {p['current_ddi_hits_lower']} | **{p['hits_with_alias_applied']}** | {p['atc_ceiling_pairs']} |")
    w("")
    w("## Q5：若 DB 有 ATC 欄位，可做 ATC-based 分析的藥對上限")
    w("")
    w("（「ATC 雙邊覆蓋」＝兩個藥的 ODR_CODE 都在 `atc_drugs.csv` 命中 → 都可指派 ATC 代碼）")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| 可對 ATC 的藥對總數 | {r['q5_total_pairs_both_atc_covered']} |")
    w(f"| ATC 覆蓋率（藥對權重） | {r['q5_atc_ceiling_pct']}% |")
    w(f"| 字串比對 DDI 命中率（exact） | {r['q5_current_match_pct_exact']}% |")
    w(f"| 字串比對 DDI 命中率（lower） | {r['q5_current_match_pct_lower']}% |")
    w("")
    w("**判讀**：")
    w("")
    q5_ceiling = r['q5_atc_ceiling_pct']
    q5_current = max(r['q5_current_match_pct_exact'], r['q5_current_match_pct_lower'])
    if q5_ceiling > q5_current * 1.5:
        w(f"- ATC 上限 ({q5_ceiling}%) 遠高於最佳 case 現行 ({q5_current}%)，PR-3 切 ATC 比對後 DDI 命中可望大幅增加。")
    elif q5_ceiling > q5_current:
        w(f"- ATC 上限 ({q5_ceiling}%) 略高於最佳 case 現行 ({q5_current}%)，PR-3 有改善空間但不戲劇性。")
    else:
        w(f"- ATC 上限 ({q5_ceiling}%) 沒有比最佳 case 現行 ({q5_current}%) 好，`atc_drugs.csv` 擴表優先度高於 PR-3 程式改動。")
    w("")
    w("> 注意：`drug_interactions` 表以藥名字串索引，並沒有 ATC 欄位。要真的切 ATC 比對需：(a) 擴 `drug_interactions` 新增 ATC 欄、(b) 或改用「ATC 同類 → 查 class node」的圖查詢。此 Q5 只反映「ATC 標準碼的覆蓋能力」，不是立即可啟動的開關。")
    w("")
    w("## Q6：對照表收斂可行性（ddi_alias vs atc_drugs）")
    w("")
    w("| 指標 | 值 |")
    w("|------|---:|")
    w(f"| `his_ddi_alias_map.json` ODR_CODE 數 | {r['q6_ddi_alias_codes']} |")
    w(f"| `atc_drugs.csv` ODR_CODE 數 | {r['q6_atc_csv_codes']} |")
    w(f"| 交集 | {r['q6_overlap']} |")
    w(f"| DB 有此 ODR_CODE 且被 alias map 覆蓋 | {r['q6_db_odr_covered_by_alias']} ({r['q6_db_odr_covered_by_alias_pct']}%) |")
    w("")
    w("### 只在 DDI alias 但不在 atc_drugs（前 20）")
    w("")
    for c in r['q6_only_alias_not_atc']:
        w(f"- `{c}`")
    w("")
    w("### 只在 atc_drugs 但不在 DDI alias（前 20）")
    w("")
    for c in r['q6_only_atc_not_alias']:
        w(f"- `{c}`")
    w("")
    w("---")
    w("")
    w("## 下一步建議（基於實測）")
    w("")
    w("### 已知事實")
    w("")
    w(f"- Q1 ODR→ATC 列權重命中率 **{r['q1_row_weighted_pct']}%**，atc_drugs.csv 對現有資料覆蓋合格")
    w(f"- Q3 HIS LAB_CODE→loinc_labs.csv 交集僅 **{r['q3_overlap_pct']}%**，`loinc_labs.csv` 對本院幫助有限；原計畫 PR-3 的 Lab 段**改用既有 `his_lab_mapping.py` + `loinc_map.py` 二段對應**即可")
    w(f"- Q4 DDI production 命中 **0**，原因不是字串格式（alias 套用也 0），是 **DDI 表缺 ICU 實際用藥組合的 entry**")
    w(f"- Q5 ATC 藥對覆蓋 **{r['q5_atc_ceiling_pct']}%**，遠高於現行 0%，但要真的啟動需擴 `drug_interactions` 或接圖查詢")
    w(f"- Q6 `his_ddi_alias_map.json` 與 `atc_drugs.csv` 只交集 **{r['q6_overlap']}** 條，兩表有收斂空間")
    w("")
    w("### 修正後的計畫")
    w("")
    w("原 PR-1~5 計畫需**調整優先順序**。")
    w("")
    w("**立即做（不等 FHIR 整合）**：")
    w("")
    w("- **決策點 D1**：DDI 系統目前靜默失效，要不要先獨立修？")
    w("  - 選項 A：先不修，接受現狀；FHIR 整合完成後再一起處理（保留 2-4 週風險窗口）")
    w("  - 選項 B：在 FHIR 前插一個 hotfix PR，至少做「name token 正規化 + 套 alias map」讓可能的 51 個 match 先啟動 — 但本次實測證明這條路命中仍是 0，所以效益可能是 0")
    w("  - 選項 C：做 DDI 重建 — 給 `drug_interactions` 加 ATC 欄位、seed 一批 ATC class-level 規則，再改 query 走 ATC 比對（工時 1-2 天）")
    w("")
    w("**FHIR 整合原計畫調整**：")
    w("")
    w("1. **PR-1（維持）**：搬 `atc_drugs.csv` 到 `backend/app/fhir/code_maps/`，寫 `atc_map()`。**放棄搬 `loinc_labs.csv`**（Q3 證明效益有限）。")
    w("2. **PR-2（維持）**：RxNorm cache-only 模式")
    w("3. **PR-3（調整）**：`medications` 加 ATC 欄位、`lab_data` 的 JSONB 補 LOINC（但 LOINC 來源改用 `loinc_map.py`）")
    w("4. **PR-3.5（新增）**：解決選項 C — DDI 改用 ATC 比對；這才是 Q4=0 的真正解法")
    w("5. **PR-4（維持）**：Coverage report")
    w("6. **PR-5（降低優先）**：On-demand Bundle export — 有 ATC/LOINC 之後自然可做，但非緊急")
    w("")
    w("**先擴 `atc_drugs.csv` 的優先項**（依 Q2 top-30 × 病人覆蓋）：")
    w("")
    w("- 前 5 名（不在 exclusion、不在 DDI alias）：`OKEPP1`（Keppra/Levetiracetam）、`OMOSA3`（Mosapride）、`OPLAV1`（Clopidogrel）、`OBISO4`（Bisoprolol）、`OSHEC1`（Bromhexine）")
    w("- 前 6 名（已在 DDI alias，補 ATC 即可對齊兩表）：`ICRAV2`（Levofloxacin）、`ICOLI1`（Colistin）、`IGENT1`（Gentamicin）、`INIMB1`（Cisatracurium）、`OEDAR1`（Azilsartan）、`ICOLI1N`（Colistin）")
    w("")
    w("---")
    w("")
    w("**重跑方式**：")
    w("")
    w("```bash")
    w("export SYNC_ENV_PATH=/Users/chun/Workspace/ChatICU_2026_verf_0110_Yu/backend/.env.his-sync")
    w("python3 /Users/chun/Workspace/ChatICU_2026_verf_0110_Yu/backend/scripts/fhir_baseline_audit.py")
    w("```")
    w("")
    return "\n".join(lines)


async def main() -> int:
    try:
        results = await audit()
    except Exception as e:
        print(f"[ERR] audit failed: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1

    # Extra sets for markdown rendering
    results["_ddi_exclusion_set"] = load_ddi_exclusion()
    results["_ddi_alias_set"] = set(load_ddi_alias().keys())

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    md = render_markdown(results)
    OUTPUT_MD.write_text(md, encoding="utf-8")

    # Print brief summary to stdout
    print(f"[OK] Baseline report written to {OUTPUT_MD}")
    print(f"     Q1 ODR→ATC (row weighted): {results['q1_row_weighted_pct']}%")
    print(f"     Q3 LAB→LOINC overlap:       {results['q3_overlap_pct']}%")
    print(f"     Q4 active pairs: {results['q4_total_unique_active_pairs']}")
    print(f"     Q4 DDI hits exact/lower: {results['q4_total_current_ddi_hits_exact']} / {results['q4_total_current_ddi_hits_lower']}")
    print(f"     Q5 ATC ceiling:             {results['q5_atc_ceiling_pct']}%")
    print(f"     Q6 alias∩atc overlap:       {results['q6_overlap']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
